-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity multi_axi is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_0_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_0_TVALID : IN STD_LOGIC;
    in_0_TREADY : OUT STD_LOGIC;
    in_1_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_1_TVALID : IN STD_LOGIC;
    in_1_TREADY : OUT STD_LOGIC;
    in_2_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_2_TVALID : IN STD_LOGIC;
    in_2_TREADY : OUT STD_LOGIC;
    in_3_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_3_TVALID : IN STD_LOGIC;
    in_3_TREADY : OUT STD_LOGIC;
    in_0_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_1_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_2_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_3_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_0_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_1_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_2_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_3_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_3_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_0_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_0_TVALID : OUT STD_LOGIC;
    out_0_TREADY : IN STD_LOGIC;
    out_1_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_1_TVALID : OUT STD_LOGIC;
    out_1_TREADY : IN STD_LOGIC;
    out_2_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_2_TVALID : OUT STD_LOGIC;
    out_2_TREADY : IN STD_LOGIC;
    out_3_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_3_TVALID : OUT STD_LOGIC;
    out_3_TREADY : IN STD_LOGIC;
    out_0_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_1_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_2_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_3_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_0_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_1_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_2_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_3_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_0_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_1_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_2_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_3_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of multi_axi is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "multi_axi,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.860500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=166,HLS_SYN_LUT=583,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal state : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal in_0_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_nbreadreq_fu_106_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_nbreadreq_fu_120_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_nbreadreq_fu_134_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_nbreadreq_fu_148_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_1_TDATA_blk_n : STD_LOGIC;
    signal in_2_TDATA_blk_n : STD_LOGIC;
    signal in_3_TDATA_blk_n : STD_LOGIC;
    signal out_0_TDATA_blk_n : STD_LOGIC;
    signal state_load_load_fu_342_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal state_load_reg_478 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal out_1_TDATA_blk_n : STD_LOGIC;
    signal out_2_TDATA_blk_n : STD_LOGIC;
    signal out_3_TDATA_blk_n : STD_LOGIC;
    signal ap_predicate_op59_read_state2 : BOOLEAN;
    signal ap_predicate_op63_read_state2 : BOOLEAN;
    signal ap_predicate_op67_read_state2 : BOOLEAN;
    signal ap_predicate_op71_read_state2 : BOOLEAN;
    signal ap_block_state2 : BOOLEAN;
    signal ap_predicate_op77_write_state2 : BOOLEAN;
    signal ap_predicate_op79_write_state2 : BOOLEAN;
    signal ap_predicate_op81_write_state2 : BOOLEAN;
    signal ap_predicate_op83_write_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal tmp_data_V_1_reg_406 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_keep_V_1_reg_414 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_V_1_reg_422 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_data_V_2_reg_430 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_keep_V_2_reg_438 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_V_2_reg_446 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_data_V_3_reg_454 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_keep_V_3_reg_462 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_V_3_reg_470 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal regslice_both_out_0_V_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_1_V_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_2_V_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_3_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state6 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal out_0_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal out_0_TVALID_int : STD_LOGIC;
    signal out_0_TREADY_int : STD_LOGIC;
    signal regslice_both_out_0_V_data_V_U_vld_out : STD_LOGIC;
    signal out_1_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal out_1_TVALID_int : STD_LOGIC;
    signal out_1_TREADY_int : STD_LOGIC;
    signal regslice_both_out_1_V_data_V_U_vld_out : STD_LOGIC;
    signal out_2_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal out_2_TVALID_int : STD_LOGIC;
    signal out_2_TREADY_int : STD_LOGIC;
    signal regslice_both_out_2_V_data_V_U_vld_out : STD_LOGIC;
    signal out_3_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal out_3_TVALID_int : STD_LOGIC;
    signal out_3_TREADY_int : STD_LOGIC;
    signal regslice_both_out_3_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_0_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal out_0_TKEEP_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_0_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_0_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_1_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal out_1_TKEEP_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_1_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_1_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_2_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal out_2_TKEEP_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_2_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_2_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_3_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal out_3_TKEEP_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_3_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_3_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_0_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal out_0_TSTRB_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_0_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_0_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_1_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal out_1_TSTRB_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_1_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_1_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_2_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal out_2_TSTRB_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_2_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_2_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_3_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal out_3_TSTRB_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_3_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_3_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_0_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_0_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_0_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_0_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_1_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_1_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_1_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_1_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_2_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_2_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_2_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_2_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_3_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_3_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_3_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_3_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_condition_259 : BOOLEAN;

    component multi_axi_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    multi_axi_control_s_axi_U : component multi_axi_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_out_0_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_0_TDATA_int,
        vld_in => out_0_TVALID_int,
        ack_in => out_0_TREADY_int,
        data_out => out_0_TDATA,
        vld_out => regslice_both_out_0_V_data_V_U_vld_out,
        ack_out => out_0_TREADY,
        apdone_blk => regslice_both_out_0_V_data_V_U_apdone_blk);

    regslice_both_out_1_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_1_TDATA_int,
        vld_in => out_1_TVALID_int,
        ack_in => out_1_TREADY_int,
        data_out => out_1_TDATA,
        vld_out => regslice_both_out_1_V_data_V_U_vld_out,
        ack_out => out_1_TREADY,
        apdone_blk => regslice_both_out_1_V_data_V_U_apdone_blk);

    regslice_both_out_2_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_2_TDATA_int,
        vld_in => out_2_TVALID_int,
        ack_in => out_2_TREADY_int,
        data_out => out_2_TDATA,
        vld_out => regslice_both_out_2_V_data_V_U_vld_out,
        ack_out => out_2_TREADY,
        apdone_blk => regslice_both_out_2_V_data_V_U_apdone_blk);

    regslice_both_out_3_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_3_TDATA_int,
        vld_in => out_3_TVALID_int,
        ack_in => out_3_TREADY_int,
        data_out => out_3_TDATA,
        vld_out => regslice_both_out_3_V_data_V_U_vld_out,
        ack_out => out_3_TREADY,
        apdone_blk => regslice_both_out_3_V_data_V_U_apdone_blk);

    regslice_both_out_0_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_0_TKEEP_int,
        vld_in => out_0_TVALID_int,
        ack_in => regslice_both_out_0_V_keep_V_U_ack_in_dummy,
        data_out => out_0_TKEEP,
        vld_out => regslice_both_out_0_V_keep_V_U_vld_out,
        ack_out => out_0_TREADY,
        apdone_blk => regslice_both_out_0_V_keep_V_U_apdone_blk);

    regslice_both_out_1_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_1_TKEEP_int,
        vld_in => out_1_TVALID_int,
        ack_in => regslice_both_out_1_V_keep_V_U_ack_in_dummy,
        data_out => out_1_TKEEP,
        vld_out => regslice_both_out_1_V_keep_V_U_vld_out,
        ack_out => out_1_TREADY,
        apdone_blk => regslice_both_out_1_V_keep_V_U_apdone_blk);

    regslice_both_out_2_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_2_TKEEP_int,
        vld_in => out_2_TVALID_int,
        ack_in => regslice_both_out_2_V_keep_V_U_ack_in_dummy,
        data_out => out_2_TKEEP,
        vld_out => regslice_both_out_2_V_keep_V_U_vld_out,
        ack_out => out_2_TREADY,
        apdone_blk => regslice_both_out_2_V_keep_V_U_apdone_blk);

    regslice_both_out_3_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_3_TKEEP_int,
        vld_in => out_3_TVALID_int,
        ack_in => regslice_both_out_3_V_keep_V_U_ack_in_dummy,
        data_out => out_3_TKEEP,
        vld_out => regslice_both_out_3_V_keep_V_U_vld_out,
        ack_out => out_3_TREADY,
        apdone_blk => regslice_both_out_3_V_keep_V_U_apdone_blk);

    regslice_both_out_0_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_0_TSTRB_int,
        vld_in => out_0_TVALID_int,
        ack_in => regslice_both_out_0_V_strb_V_U_ack_in_dummy,
        data_out => out_0_TSTRB,
        vld_out => regslice_both_out_0_V_strb_V_U_vld_out,
        ack_out => out_0_TREADY,
        apdone_blk => regslice_both_out_0_V_strb_V_U_apdone_blk);

    regslice_both_out_1_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_1_TSTRB_int,
        vld_in => out_1_TVALID_int,
        ack_in => regslice_both_out_1_V_strb_V_U_ack_in_dummy,
        data_out => out_1_TSTRB,
        vld_out => regslice_both_out_1_V_strb_V_U_vld_out,
        ack_out => out_1_TREADY,
        apdone_blk => regslice_both_out_1_V_strb_V_U_apdone_blk);

    regslice_both_out_2_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_2_TSTRB_int,
        vld_in => out_2_TVALID_int,
        ack_in => regslice_both_out_2_V_strb_V_U_ack_in_dummy,
        data_out => out_2_TSTRB,
        vld_out => regslice_both_out_2_V_strb_V_U_vld_out,
        ack_out => out_2_TREADY,
        apdone_blk => regslice_both_out_2_V_strb_V_U_apdone_blk);

    regslice_both_out_3_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_3_TSTRB_int,
        vld_in => out_3_TVALID_int,
        ack_in => regslice_both_out_3_V_strb_V_U_ack_in_dummy,
        data_out => out_3_TSTRB,
        vld_out => regslice_both_out_3_V_strb_V_U_vld_out,
        ack_out => out_3_TREADY,
        apdone_blk => regslice_both_out_3_V_strb_V_U_apdone_blk);

    regslice_both_out_0_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_0_TLAST_int,
        vld_in => out_0_TVALID_int,
        ack_in => regslice_both_out_0_V_last_V_U_ack_in_dummy,
        data_out => out_0_TLAST,
        vld_out => regslice_both_out_0_V_last_V_U_vld_out,
        ack_out => out_0_TREADY,
        apdone_blk => regslice_both_out_0_V_last_V_U_apdone_blk);

    regslice_both_out_1_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_1_TLAST_int,
        vld_in => out_1_TVALID_int,
        ack_in => regslice_both_out_1_V_last_V_U_ack_in_dummy,
        data_out => out_1_TLAST,
        vld_out => regslice_both_out_1_V_last_V_U_vld_out,
        ack_out => out_1_TREADY,
        apdone_blk => regslice_both_out_1_V_last_V_U_apdone_blk);

    regslice_both_out_2_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_2_TLAST_int,
        vld_in => out_2_TVALID_int,
        ack_in => regslice_both_out_2_V_last_V_U_ack_in_dummy,
        data_out => out_2_TLAST,
        vld_out => regslice_both_out_2_V_last_V_U_vld_out,
        ack_out => out_2_TREADY,
        apdone_blk => regslice_both_out_2_V_last_V_U_apdone_blk);

    regslice_both_out_3_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_3_TLAST_int,
        vld_in => out_3_TVALID_int,
        ack_in => regslice_both_out_3_V_last_V_U_ack_in_dummy,
        data_out => out_3_TLAST,
        vld_out => regslice_both_out_3_V_last_V_U_vld_out,
        ack_out => out_3_TREADY,
        apdone_blk => regslice_both_out_3_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_259)) then
                if ((state = ap_const_lv4_0)) then 
                    state(0) <= '1';
                    state(1) <= '0';
                elsif ((state = ap_const_lv4_1)) then 
                    state(0) <= '0';
                    state(1) <= '1';
                elsif ((state = ap_const_lv4_2)) then 
                    state(0) <= '1';
                    state(1) <= '1';
                elsif ((state = ap_const_lv4_3)) then 
                    state(0) <= '0';
                    state(1) <= '0';
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    state_load_reg_478(1 downto 0) <= state(1 downto 0);
                tmp_data_V_1_reg_406 <= in_1_TDATA;
                tmp_data_V_2_reg_430 <= in_2_TDATA;
                tmp_data_V_3_reg_454 <= in_3_TDATA;
                tmp_keep_V_1_reg_414 <= in_1_TKEEP;
                tmp_keep_V_2_reg_438 <= in_2_TKEEP;
                tmp_keep_V_3_reg_462 <= in_3_TKEEP;
                tmp_strb_V_1_reg_422 <= in_1_TSTRB;
                tmp_strb_V_2_reg_446 <= in_2_TSTRB;
                tmp_strb_V_3_reg_470 <= in_3_TSTRB;
            end if;
        end if;
    end process;
    state(3 downto 2) <= "00";
    state_load_reg_478(3 downto 2) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, state, ap_CS_fsm_state2, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6, state_load_load_fu_342_p1, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_block_state2_io, ap_block_state3_io, ap_block_state4_io, ap_block_state5_io, regslice_both_out_0_V_data_V_U_apdone_blk, regslice_both_out_1_V_data_V_U_apdone_blk, regslice_both_out_2_V_data_V_U_apdone_blk, regslice_both_out_3_V_data_V_U_apdone_blk, ap_block_state6_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and not((state = ap_const_lv4_3)) and not((state = ap_const_lv4_2)) and not((state = ap_const_lv4_1)) and not((state = ap_const_lv4_0)) and (tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                elsif ((not((state_load_load_fu_342_p1 = ap_const_lv4_F)) and not((state_load_load_fu_342_p1 = ap_const_lv4_E)) and not((state_load_load_fu_342_p1 = ap_const_lv4_D)) and not((state_load_load_fu_342_p1 = ap_const_lv4_C)) and not((state_load_load_fu_342_p1 = ap_const_lv4_B)) and not((state_load_load_fu_342_p1 = ap_const_lv4_A)) and not((state_load_load_fu_342_p1 = ap_const_lv4_9)) and not((state_load_load_fu_342_p1 = ap_const_lv4_8)) and not((state_load_load_fu_342_p1 = ap_const_lv4_7)) and not((state_load_load_fu_342_p1 = ap_const_lv4_6)) and not((state_load_load_fu_342_p1 = ap_const_lv4_5)) and not((state_load_load_fu_342_p1 = ap_const_lv4_4)) and not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((tmp_nbreadreq_fu_106_p6 = ap_const_lv1_0) or ((tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_0) or ((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_0) or (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_0)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_fsm_state3) and ((state_load_reg_478 = ap_const_lv4_0) or ((state_load_reg_478 = ap_const_lv4_1) or ((state_load_reg_478 = ap_const_lv4_3) or (state_load_reg_478 = ap_const_lv4_2)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_io) and (ap_const_logic_1 = ap_CS_fsm_state4) and ((state_load_reg_478 = ap_const_lv4_0) or ((state_load_reg_478 = ap_const_lv4_1) or ((state_load_reg_478 = ap_const_lv4_3) or (state_load_reg_478 = ap_const_lv4_2)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5_io) and (ap_const_logic_1 = ap_CS_fsm_state5) and ((state_load_reg_478 = ap_const_lv4_0) or ((state_load_reg_478 = ap_const_lv4_1) or ((state_load_reg_478 = ap_const_lv4_3) or (state_load_reg_478 = ap_const_lv4_2)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if ((not(((ap_const_boolean_1 = ap_block_state6_io) or (regslice_both_out_3_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_2_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_1_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_0_V_data_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_block_state2_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2)
    begin
                ap_block_state2 <= (((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)));
    end process;


    ap_block_state2_io_assign_proc : process(ap_predicate_op77_write_state2, ap_predicate_op79_write_state2, ap_predicate_op81_write_state2, ap_predicate_op83_write_state2, out_0_TREADY_int, out_1_TREADY_int, out_2_TREADY_int, out_3_TREADY_int)
    begin
                ap_block_state2_io <= (((out_0_TREADY_int = ap_const_logic_0) and (ap_predicate_op83_write_state2 = ap_const_boolean_1)) or ((out_1_TREADY_int = ap_const_logic_0) and (ap_predicate_op81_write_state2 = ap_const_boolean_1)) or ((out_2_TREADY_int = ap_const_logic_0) and (ap_predicate_op79_write_state2 = ap_const_boolean_1)) or ((out_3_TREADY_int = ap_const_logic_0) and (ap_predicate_op77_write_state2 = ap_const_boolean_1)));
    end process;


    ap_block_state3_io_assign_proc : process(state_load_reg_478, out_0_TREADY_int, out_1_TREADY_int, out_2_TREADY_int, out_3_TREADY_int)
    begin
                ap_block_state3_io <= (((out_3_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_3)) or ((out_2_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_2)) or ((out_1_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_1)) or ((state_load_reg_478 = ap_const_lv4_0) and (out_0_TREADY_int = ap_const_logic_0)));
    end process;


    ap_block_state4_io_assign_proc : process(state_load_reg_478, out_0_TREADY_int, out_1_TREADY_int, out_2_TREADY_int, out_3_TREADY_int)
    begin
                ap_block_state4_io <= (((out_3_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_3)) or ((out_2_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_2)) or ((out_1_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_1)) or ((state_load_reg_478 = ap_const_lv4_0) and (out_0_TREADY_int = ap_const_logic_0)));
    end process;


    ap_block_state5_io_assign_proc : process(state_load_reg_478, out_0_TREADY_int, out_1_TREADY_int, out_2_TREADY_int, out_3_TREADY_int)
    begin
                ap_block_state5_io <= (((out_3_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_3)) or ((out_2_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_2)) or ((out_1_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_1)) or ((state_load_reg_478 = ap_const_lv4_0) and (out_0_TREADY_int = ap_const_logic_0)));
    end process;


    ap_block_state6_assign_proc : process(regslice_both_out_0_V_data_V_U_apdone_blk, regslice_both_out_1_V_data_V_U_apdone_blk, regslice_both_out_2_V_data_V_U_apdone_blk, regslice_both_out_3_V_data_V_U_apdone_blk)
    begin
                ap_block_state6 <= ((regslice_both_out_3_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_2_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_1_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_0_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_block_state6_io_assign_proc : process(state_load_reg_478, out_0_TREADY_int, out_1_TREADY_int, out_2_TREADY_int, out_3_TREADY_int)
    begin
                ap_block_state6_io <= (((out_3_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_3)) or ((out_2_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_2)) or ((out_1_TREADY_int = ap_const_logic_0) and (state_load_reg_478 = ap_const_lv4_1)) or ((state_load_reg_478 = ap_const_lv4_0) and (out_0_TREADY_int = ap_const_logic_0)));
    end process;


    ap_condition_259_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_block_state2_io)
    begin
                ap_condition_259 <= (not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state6, regslice_both_out_0_V_data_V_U_apdone_blk, regslice_both_out_1_V_data_V_U_apdone_blk, regslice_both_out_2_V_data_V_U_apdone_blk, regslice_both_out_3_V_data_V_U_apdone_blk, ap_block_state6_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state6_io) or (regslice_both_out_3_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_2_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_1_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_0_V_data_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op59_read_state2_assign_proc : process(tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
                ap_predicate_op59_read_state2 <= ((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1));
    end process;


    ap_predicate_op63_read_state2_assign_proc : process(tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
                ap_predicate_op63_read_state2 <= ((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1));
    end process;


    ap_predicate_op67_read_state2_assign_proc : process(tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
                ap_predicate_op67_read_state2 <= ((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1));
    end process;


    ap_predicate_op71_read_state2_assign_proc : process(tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
                ap_predicate_op71_read_state2 <= ((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1));
    end process;


    ap_predicate_op77_write_state2_assign_proc : process(state, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
                ap_predicate_op77_write_state2 <= ((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (state = ap_const_lv4_3));
    end process;


    ap_predicate_op79_write_state2_assign_proc : process(state, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
                ap_predicate_op79_write_state2 <= ((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (state = ap_const_lv4_2));
    end process;


    ap_predicate_op81_write_state2_assign_proc : process(state, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
                ap_predicate_op81_write_state2 <= ((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (state = ap_const_lv4_1));
    end process;


    ap_predicate_op83_write_state2_assign_proc : process(state, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
                ap_predicate_op83_write_state2 <= ((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (state = ap_const_lv4_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, regslice_both_out_0_V_data_V_U_apdone_blk, regslice_both_out_1_V_data_V_U_apdone_blk, regslice_both_out_2_V_data_V_U_apdone_blk, regslice_both_out_3_V_data_V_U_apdone_blk, ap_block_state6_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state6_io) or (regslice_both_out_3_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_2_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_1_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out_0_V_data_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    in_0_TDATA_blk_n_assign_proc : process(in_0_TVALID, ap_CS_fsm_state2, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
        if (((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_0_TDATA_blk_n <= in_0_TVALID;
        else 
            in_0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_0_TREADY_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_block_state2_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op59_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_0_TREADY <= ap_const_logic_1;
        else 
            in_0_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    in_1_TDATA_blk_n_assign_proc : process(in_1_TVALID, ap_CS_fsm_state2, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
        if (((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_1_TDATA_blk_n <= in_1_TVALID;
        else 
            in_1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_1_TREADY_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_block_state2_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op63_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_1_TREADY <= ap_const_logic_1;
        else 
            in_1_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    in_2_TDATA_blk_n_assign_proc : process(in_2_TVALID, ap_CS_fsm_state2, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
        if (((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_2_TDATA_blk_n <= in_2_TVALID;
        else 
            in_2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_2_TREADY_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_block_state2_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op67_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_2_TREADY <= ap_const_logic_1;
        else 
            in_2_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    in_3_TDATA_blk_n_assign_proc : process(in_3_TVALID, ap_CS_fsm_state2, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6)
    begin
        if (((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_3_TDATA_blk_n <= in_3_TVALID;
        else 
            in_3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_3_TREADY_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_block_state2_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op71_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_3_TREADY <= ap_const_logic_1;
        else 
            in_3_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    out_0_TDATA_blk_n_assign_proc : process(state, ap_CS_fsm_state2, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, out_0_TREADY_int)
    begin
        if ((((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (state = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            out_0_TDATA_blk_n <= out_0_TREADY_int;
        else 
            out_0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_0_TDATA_int_assign_proc : process(in_0_TDATA, in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op83_write_state2, tmp_data_V_1_reg_406, tmp_data_V_2_reg_430, tmp_data_V_3_reg_454)
    begin
        if (((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_0_TDATA_int <= tmp_data_V_3_reg_454;
        elsif (((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_0_TDATA_int <= tmp_data_V_2_reg_430;
        elsif (((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            out_0_TDATA_int <= tmp_data_V_1_reg_406;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op83_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_0_TDATA_int <= in_0_TDATA;
        else 
            out_0_TDATA_int <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    out_0_TKEEP_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, in_0_TKEEP, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op83_write_state2, tmp_keep_V_1_reg_414, tmp_keep_V_2_reg_438, tmp_keep_V_3_reg_462)
    begin
        if (((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_0_TKEEP_int <= tmp_keep_V_3_reg_462;
        elsif (((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_0_TKEEP_int <= tmp_keep_V_2_reg_438;
        elsif (((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            out_0_TKEEP_int <= tmp_keep_V_1_reg_414;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op83_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_0_TKEEP_int <= in_0_TKEEP;
        else 
            out_0_TKEEP_int <= "XXXX";
        end if; 
    end process;


    out_0_TLAST_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op83_write_state2)
    begin
        if (((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_0_TLAST_int <= ap_const_lv1_1;
        elsif (((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op83_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            out_0_TLAST_int <= ap_const_lv1_0;
        else 
            out_0_TLAST_int <= "X";
        end if; 
    end process;


    out_0_TSTRB_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, in_0_TSTRB, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op83_write_state2, tmp_strb_V_1_reg_422, tmp_strb_V_2_reg_446, tmp_strb_V_3_reg_470)
    begin
        if (((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_0_TSTRB_int <= tmp_strb_V_3_reg_470;
        elsif (((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_0_TSTRB_int <= tmp_strb_V_2_reg_446;
        elsif (((state_load_reg_478 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            out_0_TSTRB_int <= tmp_strb_V_1_reg_422;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op83_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_0_TSTRB_int <= in_0_TSTRB;
        else 
            out_0_TSTRB_int <= "XXXX";
        end if; 
    end process;

    out_0_TVALID <= regslice_both_out_0_V_data_V_U_vld_out;

    out_0_TVALID_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op83_write_state2, ap_block_state2_io, ap_block_state3_io, ap_block_state4_io, ap_block_state5_io)
    begin
        if (((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op83_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((state_load_reg_478 = ap_const_lv4_0) and (ap_const_boolean_0 = ap_block_state5_io) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((state_load_reg_478 = ap_const_lv4_0) and (ap_const_boolean_0 = ap_block_state4_io) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((state_load_reg_478 = ap_const_lv4_0) and (ap_const_boolean_0 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            out_0_TVALID_int <= ap_const_logic_1;
        else 
            out_0_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    out_1_TDATA_blk_n_assign_proc : process(state, ap_CS_fsm_state2, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, out_1_TREADY_int)
    begin
        if ((((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (state = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (state_load_reg_478 = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_1)))) then 
            out_1_TDATA_blk_n <= out_1_TREADY_int;
        else 
            out_1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_1_TDATA_int_assign_proc : process(in_0_TDATA, in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op81_write_state2, tmp_data_V_1_reg_406, tmp_data_V_2_reg_430, tmp_data_V_3_reg_454)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_1))) then 
            out_1_TDATA_int <= tmp_data_V_3_reg_454;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_1))) then 
            out_1_TDATA_int <= tmp_data_V_2_reg_430;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_1))) then 
            out_1_TDATA_int <= tmp_data_V_1_reg_406;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op81_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_1_TDATA_int <= in_0_TDATA;
        else 
            out_1_TDATA_int <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    out_1_TKEEP_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, in_0_TKEEP, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op81_write_state2, tmp_keep_V_1_reg_414, tmp_keep_V_2_reg_438, tmp_keep_V_3_reg_462)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_1))) then 
            out_1_TKEEP_int <= tmp_keep_V_3_reg_462;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_1))) then 
            out_1_TKEEP_int <= tmp_keep_V_2_reg_438;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_1))) then 
            out_1_TKEEP_int <= tmp_keep_V_1_reg_414;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op81_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_1_TKEEP_int <= in_0_TKEEP;
        else 
            out_1_TKEEP_int <= "XXXX";
        end if; 
    end process;


    out_1_TLAST_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op81_write_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_1))) then 
            out_1_TLAST_int <= ap_const_lv1_1;
        elsif (((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op81_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_1)))) then 
            out_1_TLAST_int <= ap_const_lv1_0;
        else 
            out_1_TLAST_int <= "X";
        end if; 
    end process;


    out_1_TSTRB_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, in_0_TSTRB, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op81_write_state2, tmp_strb_V_1_reg_422, tmp_strb_V_2_reg_446, tmp_strb_V_3_reg_470)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_1))) then 
            out_1_TSTRB_int <= tmp_strb_V_3_reg_470;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_1))) then 
            out_1_TSTRB_int <= tmp_strb_V_2_reg_446;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_1))) then 
            out_1_TSTRB_int <= tmp_strb_V_1_reg_422;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op81_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_1_TSTRB_int <= in_0_TSTRB;
        else 
            out_1_TSTRB_int <= "XXXX";
        end if; 
    end process;

    out_1_TVALID <= regslice_both_out_1_V_data_V_U_vld_out;

    out_1_TVALID_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op81_write_state2, ap_block_state2_io, ap_block_state3_io, ap_block_state4_io, ap_block_state5_io)
    begin
        if (((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op81_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_boolean_0 = ap_block_state5_io) and (ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_1)) or ((ap_const_boolean_0 = ap_block_state4_io) and (ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_1)) or ((ap_const_boolean_0 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_1)))) then 
            out_1_TVALID_int <= ap_const_logic_1;
        else 
            out_1_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    out_2_TDATA_blk_n_assign_proc : process(state, ap_CS_fsm_state2, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, out_2_TREADY_int)
    begin
        if ((((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (state = ap_const_lv4_2)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (state_load_reg_478 = ap_const_lv4_2)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_2)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_2)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_2)))) then 
            out_2_TDATA_blk_n <= out_2_TREADY_int;
        else 
            out_2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_2_TDATA_int_assign_proc : process(in_0_TDATA, in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op79_write_state2, tmp_data_V_1_reg_406, tmp_data_V_2_reg_430, tmp_data_V_3_reg_454)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_2))) then 
            out_2_TDATA_int <= tmp_data_V_3_reg_454;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_2))) then 
            out_2_TDATA_int <= tmp_data_V_2_reg_430;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_2))) then 
            out_2_TDATA_int <= tmp_data_V_1_reg_406;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op79_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_2_TDATA_int <= in_0_TDATA;
        else 
            out_2_TDATA_int <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    out_2_TKEEP_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, in_0_TKEEP, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op79_write_state2, tmp_keep_V_1_reg_414, tmp_keep_V_2_reg_438, tmp_keep_V_3_reg_462)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_2))) then 
            out_2_TKEEP_int <= tmp_keep_V_3_reg_462;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_2))) then 
            out_2_TKEEP_int <= tmp_keep_V_2_reg_438;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_2))) then 
            out_2_TKEEP_int <= tmp_keep_V_1_reg_414;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op79_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_2_TKEEP_int <= in_0_TKEEP;
        else 
            out_2_TKEEP_int <= "XXXX";
        end if; 
    end process;


    out_2_TLAST_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op79_write_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_2))) then 
            out_2_TLAST_int <= ap_const_lv1_1;
        elsif (((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op79_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_2)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_2)))) then 
            out_2_TLAST_int <= ap_const_lv1_0;
        else 
            out_2_TLAST_int <= "X";
        end if; 
    end process;


    out_2_TSTRB_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, in_0_TSTRB, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op79_write_state2, tmp_strb_V_1_reg_422, tmp_strb_V_2_reg_446, tmp_strb_V_3_reg_470)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_2))) then 
            out_2_TSTRB_int <= tmp_strb_V_3_reg_470;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_2))) then 
            out_2_TSTRB_int <= tmp_strb_V_2_reg_446;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_2))) then 
            out_2_TSTRB_int <= tmp_strb_V_1_reg_422;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op79_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_2_TSTRB_int <= in_0_TSTRB;
        else 
            out_2_TSTRB_int <= "XXXX";
        end if; 
    end process;

    out_2_TVALID <= regslice_both_out_2_V_data_V_U_vld_out;

    out_2_TVALID_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op79_write_state2, ap_block_state2_io, ap_block_state3_io, ap_block_state4_io, ap_block_state5_io)
    begin
        if (((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op79_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_boolean_0 = ap_block_state5_io) and (ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_2)) or ((ap_const_boolean_0 = ap_block_state4_io) and (ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_2)) or ((ap_const_boolean_0 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_2)))) then 
            out_2_TVALID_int <= ap_const_logic_1;
        else 
            out_2_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    out_3_TDATA_blk_n_assign_proc : process(state, ap_CS_fsm_state2, tmp_nbreadreq_fu_106_p6, tmp_1_nbreadreq_fu_120_p6, tmp_2_nbreadreq_fu_134_p6, tmp_3_nbreadreq_fu_148_p6, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, out_3_TREADY_int)
    begin
        if ((((tmp_3_nbreadreq_fu_148_p6 = ap_const_lv1_1) and (tmp_2_nbreadreq_fu_134_p6 = ap_const_lv1_1) and (tmp_1_nbreadreq_fu_120_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_106_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (state = ap_const_lv4_3)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (state_load_reg_478 = ap_const_lv4_3)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_3)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_3)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_3)))) then 
            out_3_TDATA_blk_n <= out_3_TREADY_int;
        else 
            out_3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_3_TDATA_int_assign_proc : process(in_0_TDATA, in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op77_write_state2, tmp_data_V_1_reg_406, tmp_data_V_2_reg_430, tmp_data_V_3_reg_454)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_3))) then 
            out_3_TDATA_int <= tmp_data_V_3_reg_454;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_3))) then 
            out_3_TDATA_int <= tmp_data_V_2_reg_430;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_3))) then 
            out_3_TDATA_int <= tmp_data_V_1_reg_406;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op77_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_3_TDATA_int <= in_0_TDATA;
        else 
            out_3_TDATA_int <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    out_3_TKEEP_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, in_0_TKEEP, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op77_write_state2, tmp_keep_V_1_reg_414, tmp_keep_V_2_reg_438, tmp_keep_V_3_reg_462)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_3))) then 
            out_3_TKEEP_int <= tmp_keep_V_3_reg_462;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_3))) then 
            out_3_TKEEP_int <= tmp_keep_V_2_reg_438;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_3))) then 
            out_3_TKEEP_int <= tmp_keep_V_1_reg_414;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op77_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_3_TKEEP_int <= in_0_TKEEP;
        else 
            out_3_TKEEP_int <= "XXXX";
        end if; 
    end process;


    out_3_TLAST_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op77_write_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_3))) then 
            out_3_TLAST_int <= ap_const_lv1_1;
        elsif (((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op77_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_3)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_3)))) then 
            out_3_TLAST_int <= ap_const_lv1_0;
        else 
            out_3_TLAST_int <= "X";
        end if; 
    end process;


    out_3_TSTRB_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, in_0_TSTRB, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op77_write_state2, tmp_strb_V_1_reg_422, tmp_strb_V_2_reg_446, tmp_strb_V_3_reg_470)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_3))) then 
            out_3_TSTRB_int <= tmp_strb_V_3_reg_470;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_3))) then 
            out_3_TSTRB_int <= tmp_strb_V_2_reg_446;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_3))) then 
            out_3_TSTRB_int <= tmp_strb_V_1_reg_422;
        elsif ((not((((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op77_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_3_TSTRB_int <= in_0_TSTRB;
        else 
            out_3_TSTRB_int <= "XXXX";
        end if; 
    end process;

    out_3_TVALID <= regslice_both_out_3_V_data_V_U_vld_out;

    out_3_TVALID_int_assign_proc : process(in_0_TVALID, in_1_TVALID, in_2_TVALID, in_3_TVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, state_load_reg_478, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_predicate_op59_read_state2, ap_predicate_op63_read_state2, ap_predicate_op67_read_state2, ap_predicate_op71_read_state2, ap_predicate_op77_write_state2, ap_block_state2_io, ap_block_state3_io, ap_block_state4_io, ap_block_state5_io)
    begin
        if (((not(((ap_const_boolean_1 = ap_block_state2_io) or ((in_3_TVALID = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1)) or ((in_2_TVALID = ap_const_logic_0) and (ap_predicate_op67_read_state2 = ap_const_boolean_1)) or ((in_1_TVALID = ap_const_logic_0) and (ap_predicate_op63_read_state2 = ap_const_boolean_1)) or ((in_0_TVALID = ap_const_logic_0) and (ap_predicate_op59_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op77_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_boolean_0 = ap_block_state5_io) and (ap_const_logic_1 = ap_CS_fsm_state5) and (state_load_reg_478 = ap_const_lv4_3)) or ((ap_const_boolean_0 = ap_block_state4_io) and (ap_const_logic_1 = ap_CS_fsm_state4) and (state_load_reg_478 = ap_const_lv4_3)) or ((ap_const_boolean_0 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_fsm_state3) and (state_load_reg_478 = ap_const_lv4_3)))) then 
            out_3_TVALID_int <= ap_const_logic_1;
        else 
            out_3_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    state_load_load_fu_342_p1 <= state;
    tmp_1_nbreadreq_fu_120_p6 <= (0=>(in_1_TVALID), others=>'-');
    tmp_2_nbreadreq_fu_134_p6 <= (0=>(in_2_TVALID), others=>'-');
    tmp_3_nbreadreq_fu_148_p6 <= (0=>(in_3_TVALID), others=>'-');
    tmp_nbreadreq_fu_106_p6 <= (0=>(in_0_TVALID), others=>'-');
end behav;
