// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fused_cnn_layer,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.702000,HLS_SYN_LAT=449,HLS_SYN_TPT=450,HLS_SYN_MEM=17,HLS_SYN_DSP=12,HLS_SYN_FF=7687,HLS_SYN_LUT=11110,HLS_VERSION=2020_1}" *)

module fused_cnn_layer (
        in_0_TDATA,
        in_1_TDATA,
        in_0_TKEEP,
        in_1_TKEEP,
        in_0_TSTRB,
        in_1_TSTRB,
        in_0_TLAST,
        in_1_TLAST,
        out_r_TDATA,
        out_r_TKEEP,
        out_r_TSTRB,
        out_r_TLAST,
        ap_clk,
        ap_rst_n,
        in_0_TVALID,
        in_0_TREADY,
        in_1_TVALID,
        in_1_TREADY,
        out_r_TVALID,
        out_r_TREADY
);


input  [63:0] in_0_TDATA;
input  [63:0] in_1_TDATA;
input  [7:0] in_0_TKEEP;
input  [7:0] in_1_TKEEP;
input  [7:0] in_0_TSTRB;
input  [7:0] in_1_TSTRB;
input  [0:0] in_0_TLAST;
input  [0:0] in_1_TLAST;
output  [63:0] out_r_TDATA;
output  [7:0] out_r_TKEEP;
output  [7:0] out_r_TSTRB;
output  [0:0] out_r_TLAST;
input   ap_clk;
input   ap_rst_n;
input   in_0_TVALID;
output   in_0_TREADY;
input   in_1_TVALID;
output   in_1_TREADY;
output   out_r_TVALID;
input   out_r_TREADY;

 reg    ap_rst_n_inv;
wire    read_input_U0_ap_start;
wire    read_input_U0_ap_done;
wire    read_input_U0_ap_continue;
wire    read_input_U0_ap_idle;
wire    read_input_U0_ap_ready;
wire    read_input_U0_start_out;
wire    read_input_U0_start_write;
wire   [7:0] read_input_U0_input_upper_0_V_din;
wire    read_input_U0_input_upper_0_V_write;
wire   [7:0] read_input_U0_input_upper_1_V_din;
wire    read_input_U0_input_upper_1_V_write;
wire   [7:0] read_input_U0_input_upper_2_V_din;
wire    read_input_U0_input_upper_2_V_write;
wire   [7:0] read_input_U0_input_lower_0_V_din;
wire    read_input_U0_input_lower_0_V_write;
wire   [7:0] read_input_U0_input_lower_1_V_din;
wire    read_input_U0_input_lower_1_V_write;
wire   [7:0] read_input_U0_input_lower_2_V_din;
wire    read_input_U0_input_lower_2_V_write;
wire    read_input_U0_in_0_TREADY;
wire    read_input_U0_in_1_TREADY;
wire    kernel_U0_ap_start;
wire    kernel_U0_ap_done;
wire    kernel_U0_ap_continue;
wire    kernel_U0_ap_idle;
wire    kernel_U0_ap_ready;
wire    kernel_U0_start_out;
wire    kernel_U0_start_write;
wire    kernel_U0_input_upper_0_V_read;
wire    kernel_U0_input_upper_1_V_read;
wire    kernel_U0_input_upper_2_V_read;
wire    kernel_U0_input_lower_0_V_read;
wire    kernel_U0_input_lower_1_V_read;
wire    kernel_U0_input_lower_2_V_read;
wire   [15:0] kernel_U0_output_0_V_din;
wire    kernel_U0_output_0_V_write;
wire   [15:0] kernel_U0_output_1_V_din;
wire    kernel_U0_output_1_V_write;
wire   [15:0] kernel_U0_output_2_V_din;
wire    kernel_U0_output_2_V_write;
wire   [15:0] kernel_U0_output_3_V_din;
wire    kernel_U0_output_3_V_write;
wire    write_output_U0_ap_start;
wire    write_output_U0_ap_done;
wire    write_output_U0_ap_continue;
wire    write_output_U0_ap_idle;
wire    write_output_U0_ap_ready;
wire    write_output_U0_output_0_V_read;
wire    write_output_U0_output_1_V_read;
wire    write_output_U0_output_2_V_read;
wire    write_output_U0_output_3_V_read;
wire   [63:0] write_output_U0_out_r_TDATA;
wire    write_output_U0_out_r_TVALID;
wire   [7:0] write_output_U0_out_r_TKEEP;
wire   [7:0] write_output_U0_out_r_TSTRB;
wire   [0:0] write_output_U0_out_r_TLAST;
wire    ap_sync_continue;
wire    input_upper_0_V_full_n;
wire   [7:0] input_upper_0_V_dout;
wire    input_upper_0_V_empty_n;
wire    input_upper_1_V_full_n;
wire   [7:0] input_upper_1_V_dout;
wire    input_upper_1_V_empty_n;
wire    input_upper_2_V_full_n;
wire   [7:0] input_upper_2_V_dout;
wire    input_upper_2_V_empty_n;
wire    input_lower_0_V_full_n;
wire   [7:0] input_lower_0_V_dout;
wire    input_lower_0_V_empty_n;
wire    input_lower_1_V_full_n;
wire   [7:0] input_lower_1_V_dout;
wire    input_lower_1_V_empty_n;
wire    input_lower_2_V_full_n;
wire   [7:0] input_lower_2_V_dout;
wire    input_lower_2_V_empty_n;
wire    output_0_V_full_n;
wire   [15:0] output_0_V_dout;
wire    output_0_V_empty_n;
wire    output_1_V_full_n;
wire   [15:0] output_1_V_dout;
wire    output_1_V_empty_n;
wire    output_2_V_full_n;
wire   [15:0] output_2_V_dout;
wire    output_2_V_empty_n;
wire    output_3_V_full_n;
wire   [15:0] output_3_V_dout;
wire    output_3_V_empty_n;
wire   [0:0] start_for_kernel_U0_din;
wire    start_for_kernel_U0_full_n;
wire   [0:0] start_for_kernel_U0_dout;
wire    start_for_kernel_U0_empty_n;
wire   [0:0] start_for_write_output_U0_din;
wire    start_for_write_output_U0_full_n;
wire   [0:0] start_for_write_output_U0_dout;
wire    start_for_write_output_U0_empty_n;
wire    write_output_U0_start_full_n;
wire    write_output_U0_start_write;

read_input read_input_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read_input_U0_ap_start),
    .start_full_n(start_for_kernel_U0_full_n),
    .ap_done(read_input_U0_ap_done),
    .ap_continue(read_input_U0_ap_continue),
    .ap_idle(read_input_U0_ap_idle),
    .ap_ready(read_input_U0_ap_ready),
    .start_out(read_input_U0_start_out),
    .start_write(read_input_U0_start_write),
    .input_upper_0_V_din(read_input_U0_input_upper_0_V_din),
    .input_upper_0_V_full_n(input_upper_0_V_full_n),
    .input_upper_0_V_write(read_input_U0_input_upper_0_V_write),
    .input_upper_1_V_din(read_input_U0_input_upper_1_V_din),
    .input_upper_1_V_full_n(input_upper_1_V_full_n),
    .input_upper_1_V_write(read_input_U0_input_upper_1_V_write),
    .input_upper_2_V_din(read_input_U0_input_upper_2_V_din),
    .input_upper_2_V_full_n(input_upper_2_V_full_n),
    .input_upper_2_V_write(read_input_U0_input_upper_2_V_write),
    .input_lower_0_V_din(read_input_U0_input_lower_0_V_din),
    .input_lower_0_V_full_n(input_lower_0_V_full_n),
    .input_lower_0_V_write(read_input_U0_input_lower_0_V_write),
    .input_lower_1_V_din(read_input_U0_input_lower_1_V_din),
    .input_lower_1_V_full_n(input_lower_1_V_full_n),
    .input_lower_1_V_write(read_input_U0_input_lower_1_V_write),
    .input_lower_2_V_din(read_input_U0_input_lower_2_V_din),
    .input_lower_2_V_full_n(input_lower_2_V_full_n),
    .input_lower_2_V_write(read_input_U0_input_lower_2_V_write),
    .in_0_TDATA(in_0_TDATA),
    .in_0_TVALID(in_0_TVALID),
    .in_0_TREADY(read_input_U0_in_0_TREADY),
    .in_1_TDATA(in_1_TDATA),
    .in_1_TVALID(in_1_TVALID),
    .in_1_TREADY(read_input_U0_in_1_TREADY),
    .in_0_TKEEP(in_0_TKEEP),
    .in_1_TKEEP(in_1_TKEEP),
    .in_0_TSTRB(in_0_TSTRB),
    .in_1_TSTRB(in_1_TSTRB),
    .in_0_TLAST(in_0_TLAST),
    .in_1_TLAST(in_1_TLAST)
);

kernel kernel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(kernel_U0_ap_start),
    .start_full_n(start_for_write_output_U0_full_n),
    .ap_done(kernel_U0_ap_done),
    .ap_continue(kernel_U0_ap_continue),
    .ap_idle(kernel_U0_ap_idle),
    .ap_ready(kernel_U0_ap_ready),
    .start_out(kernel_U0_start_out),
    .start_write(kernel_U0_start_write),
    .input_upper_0_V_dout(input_upper_0_V_dout),
    .input_upper_0_V_empty_n(input_upper_0_V_empty_n),
    .input_upper_0_V_read(kernel_U0_input_upper_0_V_read),
    .input_upper_1_V_dout(input_upper_1_V_dout),
    .input_upper_1_V_empty_n(input_upper_1_V_empty_n),
    .input_upper_1_V_read(kernel_U0_input_upper_1_V_read),
    .input_upper_2_V_dout(input_upper_2_V_dout),
    .input_upper_2_V_empty_n(input_upper_2_V_empty_n),
    .input_upper_2_V_read(kernel_U0_input_upper_2_V_read),
    .input_lower_0_V_dout(input_lower_0_V_dout),
    .input_lower_0_V_empty_n(input_lower_0_V_empty_n),
    .input_lower_0_V_read(kernel_U0_input_lower_0_V_read),
    .input_lower_1_V_dout(input_lower_1_V_dout),
    .input_lower_1_V_empty_n(input_lower_1_V_empty_n),
    .input_lower_1_V_read(kernel_U0_input_lower_1_V_read),
    .input_lower_2_V_dout(input_lower_2_V_dout),
    .input_lower_2_V_empty_n(input_lower_2_V_empty_n),
    .input_lower_2_V_read(kernel_U0_input_lower_2_V_read),
    .output_0_V_din(kernel_U0_output_0_V_din),
    .output_0_V_full_n(output_0_V_full_n),
    .output_0_V_write(kernel_U0_output_0_V_write),
    .output_1_V_din(kernel_U0_output_1_V_din),
    .output_1_V_full_n(output_1_V_full_n),
    .output_1_V_write(kernel_U0_output_1_V_write),
    .output_2_V_din(kernel_U0_output_2_V_din),
    .output_2_V_full_n(output_2_V_full_n),
    .output_2_V_write(kernel_U0_output_2_V_write),
    .output_3_V_din(kernel_U0_output_3_V_din),
    .output_3_V_full_n(output_3_V_full_n),
    .output_3_V_write(kernel_U0_output_3_V_write)
);

write_output write_output_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(write_output_U0_ap_start),
    .ap_done(write_output_U0_ap_done),
    .ap_continue(write_output_U0_ap_continue),
    .ap_idle(write_output_U0_ap_idle),
    .ap_ready(write_output_U0_ap_ready),
    .output_0_V_dout(output_0_V_dout),
    .output_0_V_empty_n(output_0_V_empty_n),
    .output_0_V_read(write_output_U0_output_0_V_read),
    .output_1_V_dout(output_1_V_dout),
    .output_1_V_empty_n(output_1_V_empty_n),
    .output_1_V_read(write_output_U0_output_1_V_read),
    .output_2_V_dout(output_2_V_dout),
    .output_2_V_empty_n(output_2_V_empty_n),
    .output_2_V_read(write_output_U0_output_2_V_read),
    .output_3_V_dout(output_3_V_dout),
    .output_3_V_empty_n(output_3_V_empty_n),
    .output_3_V_read(write_output_U0_output_3_V_read),
    .out_r_TDATA(write_output_U0_out_r_TDATA),
    .out_r_TVALID(write_output_U0_out_r_TVALID),
    .out_r_TREADY(out_r_TREADY),
    .out_r_TKEEP(write_output_U0_out_r_TKEEP),
    .out_r_TSTRB(write_output_U0_out_r_TSTRB),
    .out_r_TLAST(write_output_U0_out_r_TLAST)
);

fifo_w8_d2_A input_upper_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_U0_input_upper_0_V_din),
    .if_full_n(input_upper_0_V_full_n),
    .if_write(read_input_U0_input_upper_0_V_write),
    .if_dout(input_upper_0_V_dout),
    .if_empty_n(input_upper_0_V_empty_n),
    .if_read(kernel_U0_input_upper_0_V_read)
);

fifo_w8_d2_A input_upper_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_U0_input_upper_1_V_din),
    .if_full_n(input_upper_1_V_full_n),
    .if_write(read_input_U0_input_upper_1_V_write),
    .if_dout(input_upper_1_V_dout),
    .if_empty_n(input_upper_1_V_empty_n),
    .if_read(kernel_U0_input_upper_1_V_read)
);

fifo_w8_d2_A input_upper_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_U0_input_upper_2_V_din),
    .if_full_n(input_upper_2_V_full_n),
    .if_write(read_input_U0_input_upper_2_V_write),
    .if_dout(input_upper_2_V_dout),
    .if_empty_n(input_upper_2_V_empty_n),
    .if_read(kernel_U0_input_upper_2_V_read)
);

fifo_w8_d2_A input_lower_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_U0_input_lower_0_V_din),
    .if_full_n(input_lower_0_V_full_n),
    .if_write(read_input_U0_input_lower_0_V_write),
    .if_dout(input_lower_0_V_dout),
    .if_empty_n(input_lower_0_V_empty_n),
    .if_read(kernel_U0_input_lower_0_V_read)
);

fifo_w8_d2_A input_lower_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_U0_input_lower_1_V_din),
    .if_full_n(input_lower_1_V_full_n),
    .if_write(read_input_U0_input_lower_1_V_write),
    .if_dout(input_lower_1_V_dout),
    .if_empty_n(input_lower_1_V_empty_n),
    .if_read(kernel_U0_input_lower_1_V_read)
);

fifo_w8_d2_A input_lower_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_U0_input_lower_2_V_din),
    .if_full_n(input_lower_2_V_full_n),
    .if_write(read_input_U0_input_lower_2_V_write),
    .if_dout(input_lower_2_V_dout),
    .if_empty_n(input_lower_2_V_empty_n),
    .if_read(kernel_U0_input_lower_2_V_read)
);

fifo_w16_d1_A output_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(kernel_U0_output_0_V_din),
    .if_full_n(output_0_V_full_n),
    .if_write(kernel_U0_output_0_V_write),
    .if_dout(output_0_V_dout),
    .if_empty_n(output_0_V_empty_n),
    .if_read(write_output_U0_output_0_V_read)
);

fifo_w16_d1_A output_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(kernel_U0_output_1_V_din),
    .if_full_n(output_1_V_full_n),
    .if_write(kernel_U0_output_1_V_write),
    .if_dout(output_1_V_dout),
    .if_empty_n(output_1_V_empty_n),
    .if_read(write_output_U0_output_1_V_read)
);

fifo_w16_d1_A output_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(kernel_U0_output_2_V_din),
    .if_full_n(output_2_V_full_n),
    .if_write(kernel_U0_output_2_V_write),
    .if_dout(output_2_V_dout),
    .if_empty_n(output_2_V_empty_n),
    .if_read(write_output_U0_output_2_V_read)
);

fifo_w16_d1_A output_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(kernel_U0_output_3_V_din),
    .if_full_n(output_3_V_full_n),
    .if_write(kernel_U0_output_3_V_write),
    .if_dout(output_3_V_dout),
    .if_empty_n(output_3_V_empty_n),
    .if_read(write_output_U0_output_3_V_read)
);

start_for_kernel_U0 start_for_kernel_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_kernel_U0_din),
    .if_full_n(start_for_kernel_U0_full_n),
    .if_write(read_input_U0_start_write),
    .if_dout(start_for_kernel_U0_dout),
    .if_empty_n(start_for_kernel_U0_empty_n),
    .if_read(kernel_U0_ap_ready)
);

start_for_write_ohbi start_for_write_ohbi_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_output_U0_din),
    .if_full_n(start_for_write_output_U0_full_n),
    .if_write(kernel_U0_start_write),
    .if_dout(start_for_write_output_U0_dout),
    .if_empty_n(start_for_write_output_U0_empty_n),
    .if_read(write_output_U0_ap_ready)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign in_0_TREADY = read_input_U0_in_0_TREADY;

assign in_1_TREADY = read_input_U0_in_1_TREADY;

assign kernel_U0_ap_continue = 1'b1;

assign kernel_U0_ap_start = start_for_kernel_U0_empty_n;

assign out_r_TDATA = write_output_U0_out_r_TDATA;

assign out_r_TKEEP = write_output_U0_out_r_TKEEP;

assign out_r_TLAST = write_output_U0_out_r_TLAST;

assign out_r_TSTRB = write_output_U0_out_r_TSTRB;

assign out_r_TVALID = write_output_U0_out_r_TVALID;

assign read_input_U0_ap_continue = 1'b1;

assign read_input_U0_ap_start = 1'b1;

assign start_for_kernel_U0_din = 1'b1;

assign start_for_write_output_U0_din = 1'b1;

assign write_output_U0_ap_continue = 1'b1;

assign write_output_U0_ap_start = start_for_write_output_U0_empty_n;

assign write_output_U0_start_full_n = 1'b1;

assign write_output_U0_start_write = 1'b0;

endmodule //fused_cnn_layer
