-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity write_output is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    output_0_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    output_0_V_empty_n : IN STD_LOGIC;
    output_0_V_read : OUT STD_LOGIC;
    output_1_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    output_1_V_empty_n : IN STD_LOGIC;
    output_1_V_read : OUT STD_LOGIC;
    output_2_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    output_2_V_empty_n : IN STD_LOGIC;
    output_2_V_read : OUT STD_LOGIC;
    output_3_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    output_3_V_empty_n : IN STD_LOGIC;
    output_3_V_read : OUT STD_LOGIC;
    out_r_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    out_r_TVALID : OUT STD_LOGIC;
    out_r_TREADY : IN STD_LOGIC;
    out_r_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_r_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of write_output is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal output_0_V_blk_n : STD_LOGIC;
    signal output_1_V_blk_n : STD_LOGIC;
    signal output_2_V_blk_n : STD_LOGIC;
    signal output_3_V_blk_n : STD_LOGIC;
    signal out_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal regslice_both_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal out_r_TDATA_int : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r_TVALID_int : STD_LOGIC;
    signal out_r_TREADY_int : STD_LOGIC;
    signal regslice_both_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_V_last_V_U_vld_out : STD_LOGIC;

    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_out_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => out_r_TDATA_int,
        vld_in => out_r_TVALID_int,
        ack_in => out_r_TREADY_int,
        data_out => out_r_TDATA,
        vld_out => regslice_both_out_V_data_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_V_data_V_U_apdone_blk);

    regslice_both_out_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv8_FF,
        vld_in => out_r_TVALID_int,
        ack_in => regslice_both_out_V_keep_V_U_ack_in_dummy,
        data_out => out_r_TKEEP,
        vld_out => regslice_both_out_V_keep_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_V_keep_V_U_apdone_blk);

    regslice_both_out_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv8_0,
        vld_in => out_r_TVALID_int,
        ack_in => regslice_both_out_V_strb_V_U_ack_in_dummy,
        data_out => out_r_TSTRB,
        vld_out => regslice_both_out_V_strb_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_V_strb_V_U_apdone_blk);

    regslice_both_out_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv1_0,
        vld_in => out_r_TVALID_int,
        ack_in => regslice_both_out_V_last_V_U_ack_in_dummy,
        data_out => out_r_TLAST,
        vld_out => regslice_both_out_V_last_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((out_r_TREADY_int = ap_const_logic_0) or (regslice_both_out_V_data_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, output_0_V_empty_n, output_1_V_empty_n, output_2_V_empty_n, output_3_V_empty_n, ap_CS_fsm_state2, regslice_both_out_V_data_V_U_apdone_blk, out_r_TREADY_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (output_3_V_empty_n = ap_const_logic_0) or (output_2_V_empty_n = ap_const_logic_0) or (output_1_V_empty_n = ap_const_logic_0) or (output_0_V_empty_n = ap_const_logic_0) or (out_r_TREADY_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((out_r_TREADY_int = ap_const_logic_0) or (regslice_both_out_V_data_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, output_0_V_empty_n, output_1_V_empty_n, output_2_V_empty_n, output_3_V_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (output_3_V_empty_n = ap_const_logic_0) or (output_2_V_empty_n = ap_const_logic_0) or (output_1_V_empty_n = ap_const_logic_0) or (output_0_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, regslice_both_out_V_data_V_U_apdone_blk, out_r_TREADY_int)
    begin
        if ((not(((out_r_TREADY_int = ap_const_logic_0) or (regslice_both_out_V_data_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, regslice_both_out_V_data_V_U_apdone_blk, out_r_TREADY_int)
    begin
        if ((not(((out_r_TREADY_int = ap_const_logic_0) or (regslice_both_out_V_data_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    out_r_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_CS_fsm_state2, out_r_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            out_r_TDATA_blk_n <= out_r_TREADY_int;
        else 
            out_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_r_TDATA_int <= (((output_3_V_dout & output_2_V_dout) & output_1_V_dout) & output_0_V_dout);
    out_r_TVALID <= regslice_both_out_V_data_V_U_vld_out;

    out_r_TVALID_int_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_0_V_empty_n, output_1_V_empty_n, output_2_V_empty_n, output_3_V_empty_n, out_r_TREADY_int)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_3_V_empty_n = ap_const_logic_0) or (output_2_V_empty_n = ap_const_logic_0) or (output_1_V_empty_n = ap_const_logic_0) or (output_0_V_empty_n = ap_const_logic_0) or (out_r_TREADY_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            out_r_TVALID_int <= ap_const_logic_1;
        else 
            out_r_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    output_0_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_0_V_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_0_V_blk_n <= output_0_V_empty_n;
        else 
            output_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_0_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_0_V_empty_n, output_1_V_empty_n, output_2_V_empty_n, output_3_V_empty_n, out_r_TREADY_int)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_3_V_empty_n = ap_const_logic_0) or (output_2_V_empty_n = ap_const_logic_0) or (output_1_V_empty_n = ap_const_logic_0) or (output_0_V_empty_n = ap_const_logic_0) or (out_r_TREADY_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_0_V_read <= ap_const_logic_1;
        else 
            output_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    output_1_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_1_V_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_1_V_blk_n <= output_1_V_empty_n;
        else 
            output_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_1_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_0_V_empty_n, output_1_V_empty_n, output_2_V_empty_n, output_3_V_empty_n, out_r_TREADY_int)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_3_V_empty_n = ap_const_logic_0) or (output_2_V_empty_n = ap_const_logic_0) or (output_1_V_empty_n = ap_const_logic_0) or (output_0_V_empty_n = ap_const_logic_0) or (out_r_TREADY_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_1_V_read <= ap_const_logic_1;
        else 
            output_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    output_2_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_2_V_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_2_V_blk_n <= output_2_V_empty_n;
        else 
            output_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_2_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_0_V_empty_n, output_1_V_empty_n, output_2_V_empty_n, output_3_V_empty_n, out_r_TREADY_int)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_3_V_empty_n = ap_const_logic_0) or (output_2_V_empty_n = ap_const_logic_0) or (output_1_V_empty_n = ap_const_logic_0) or (output_0_V_empty_n = ap_const_logic_0) or (out_r_TREADY_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_2_V_read <= ap_const_logic_1;
        else 
            output_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    output_3_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_3_V_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_3_V_blk_n <= output_3_V_empty_n;
        else 
            output_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_3_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, output_0_V_empty_n, output_1_V_empty_n, output_2_V_empty_n, output_3_V_empty_n, out_r_TREADY_int)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (output_3_V_empty_n = ap_const_logic_0) or (output_2_V_empty_n = ap_const_logic_0) or (output_1_V_empty_n = ap_const_logic_0) or (output_0_V_empty_n = ap_const_logic_0) or (out_r_TREADY_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            output_3_V_read <= ap_const_logic_1;
        else 
            output_3_V_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
