# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/matmul/matmul.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul || ORIG_REF_NAME==matmul} -quiet] -quiet

# IP: bd/matmul/ip/matmul_processing_system7_0_0/matmul_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_processing_system7_0_0 || ORIG_REF_NAME==matmul_processing_system7_0_0} -quiet] -quiet

# IP: bd/matmul/ip/matmul_matmul_0_0/matmul_matmul_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_matmul_0_0 || ORIG_REF_NAME==matmul_matmul_0_0} -quiet] -quiet

# IP: bd/matmul/ip/matmul_axi_dma_0_0/matmul_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_axi_dma_0_0 || ORIG_REF_NAME==matmul_axi_dma_0_0} -quiet] -quiet

# IP: bd/matmul/ip/matmul_proc_sys_reset_0_0/matmul_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_proc_sys_reset_0_0 || ORIG_REF_NAME==matmul_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/matmul/ip/matmul_xbar_0/matmul_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_xbar_0 || ORIG_REF_NAME==matmul_xbar_0} -quiet] -quiet

# IP: bd/matmul/ip/matmul_auto_pc_0/matmul_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_auto_pc_0 || ORIG_REF_NAME==matmul_auto_pc_0} -quiet] -quiet

# IP: bd/matmul/ip/matmul_ps7_0_axi_periph_0/matmul_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_ps7_0_axi_periph_0 || ORIG_REF_NAME==matmul_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/matmul/ip/matmul_xbar_1/matmul_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_xbar_1 || ORIG_REF_NAME==matmul_xbar_1} -quiet] -quiet

# IP: bd/matmul/ip/matmul_auto_us_0/matmul_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_auto_us_0 || ORIG_REF_NAME==matmul_auto_us_0} -quiet] -quiet

# IP: bd/matmul/ip/matmul_auto_ds_0/matmul_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_auto_ds_0 || ORIG_REF_NAME==matmul_auto_ds_0} -quiet] -quiet

# IP: bd/matmul/ip/matmul_auto_pc_1/matmul_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_auto_pc_1 || ORIG_REF_NAME==matmul_auto_pc_1} -quiet] -quiet

# IP: bd/matmul/ip/matmul_axi_mem_intercon_0/matmul_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matmul_axi_mem_intercon_0 || ORIG_REF_NAME==matmul_axi_mem_intercon_0} -quiet] -quiet

# XDC: bd/matmul/matmul_ooc.xdc
