// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cnn.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<64> cnn::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<8> cnn::ap_const_lv8_0 = "00000000";
const sc_lv<1> cnn::ap_const_lv1_0 = "0";
const sc_logic cnn::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cnn::ap_const_logic_0 = sc_dt::Log_0;

cnn::cnn(sc_module_name name) : sc_module(name), mVcdFile(0) {
    read_input_U0 = new read_input("read_input_U0");
    read_input_U0->ap_clk(ap_clk);
    read_input_U0->ap_rst(ap_rst_n_inv);
    read_input_U0->ap_start(read_input_U0_ap_start);
    read_input_U0->start_full_n(start_for_kernel_U0_full_n);
    read_input_U0->ap_done(read_input_U0_ap_done);
    read_input_U0->ap_continue(read_input_U0_ap_continue);
    read_input_U0->ap_idle(read_input_U0_ap_idle);
    read_input_U0->ap_ready(read_input_U0_ap_ready);
    read_input_U0->start_out(read_input_U0_start_out);
    read_input_U0->start_write(read_input_U0_start_write);
    read_input_U0->in_0_TDATA(in_0_TDATA);
    read_input_U0->in_0_TVALID(in_0_TVALID);
    read_input_U0->in_0_TREADY(read_input_U0_in_0_TREADY);
    read_input_U0->in_1_TDATA(in_1_TDATA);
    read_input_U0->in_1_TVALID(in_1_TVALID);
    read_input_U0->in_1_TREADY(read_input_U0_in_1_TREADY);
    read_input_U0->in_2_TDATA(in_2_TDATA);
    read_input_U0->in_2_TVALID(in_2_TVALID);
    read_input_U0->in_2_TREADY(read_input_U0_in_2_TREADY);
    read_input_U0->in_3_TDATA(in_3_TDATA);
    read_input_U0->in_3_TVALID(in_3_TVALID);
    read_input_U0->in_3_TREADY(read_input_U0_in_3_TREADY);
    read_input_U0->in_0_TKEEP(in_0_TKEEP);
    read_input_U0->in_1_TKEEP(in_1_TKEEP);
    read_input_U0->in_2_TKEEP(in_2_TKEEP);
    read_input_U0->in_3_TKEEP(in_3_TKEEP);
    read_input_U0->in_0_TSTRB(in_0_TSTRB);
    read_input_U0->in_1_TSTRB(in_1_TSTRB);
    read_input_U0->in_2_TSTRB(in_2_TSTRB);
    read_input_U0->in_3_TSTRB(in_3_TSTRB);
    read_input_U0->in_0_TLAST(in_0_TLAST);
    read_input_U0->in_1_TLAST(in_1_TLAST);
    read_input_U0->in_2_TLAST(in_2_TLAST);
    read_input_U0->in_3_TLAST(in_3_TLAST);
    read_input_U0->inputs_0_0_V_din(read_input_U0_inputs_0_0_V_din);
    read_input_U0->inputs_0_0_V_full_n(inputs_0_0_V_full_n);
    read_input_U0->inputs_0_0_V_write(read_input_U0_inputs_0_0_V_write);
    read_input_U0->inputs_0_1_V_din(read_input_U0_inputs_0_1_V_din);
    read_input_U0->inputs_0_1_V_full_n(inputs_0_1_V_full_n);
    read_input_U0->inputs_0_1_V_write(read_input_U0_inputs_0_1_V_write);
    read_input_U0->inputs_0_2_V_din(read_input_U0_inputs_0_2_V_din);
    read_input_U0->inputs_0_2_V_full_n(inputs_0_2_V_full_n);
    read_input_U0->inputs_0_2_V_write(read_input_U0_inputs_0_2_V_write);
    read_input_U0->inputs_1_0_V_din(read_input_U0_inputs_1_0_V_din);
    read_input_U0->inputs_1_0_V_full_n(inputs_1_0_V_full_n);
    read_input_U0->inputs_1_0_V_write(read_input_U0_inputs_1_0_V_write);
    read_input_U0->inputs_1_1_V_din(read_input_U0_inputs_1_1_V_din);
    read_input_U0->inputs_1_1_V_full_n(inputs_1_1_V_full_n);
    read_input_U0->inputs_1_1_V_write(read_input_U0_inputs_1_1_V_write);
    read_input_U0->inputs_1_2_V_din(read_input_U0_inputs_1_2_V_din);
    read_input_U0->inputs_1_2_V_full_n(inputs_1_2_V_full_n);
    read_input_U0->inputs_1_2_V_write(read_input_U0_inputs_1_2_V_write);
    read_input_U0->inputs_2_0_V_din(read_input_U0_inputs_2_0_V_din);
    read_input_U0->inputs_2_0_V_full_n(inputs_2_0_V_full_n);
    read_input_U0->inputs_2_0_V_write(read_input_U0_inputs_2_0_V_write);
    read_input_U0->inputs_2_1_V_din(read_input_U0_inputs_2_1_V_din);
    read_input_U0->inputs_2_1_V_full_n(inputs_2_1_V_full_n);
    read_input_U0->inputs_2_1_V_write(read_input_U0_inputs_2_1_V_write);
    read_input_U0->inputs_2_2_V_din(read_input_U0_inputs_2_2_V_din);
    read_input_U0->inputs_2_2_V_full_n(inputs_2_2_V_full_n);
    read_input_U0->inputs_2_2_V_write(read_input_U0_inputs_2_2_V_write);
    read_input_U0->inputs_3_0_V_din(read_input_U0_inputs_3_0_V_din);
    read_input_U0->inputs_3_0_V_full_n(inputs_3_0_V_full_n);
    read_input_U0->inputs_3_0_V_write(read_input_U0_inputs_3_0_V_write);
    read_input_U0->inputs_3_1_V_din(read_input_U0_inputs_3_1_V_din);
    read_input_U0->inputs_3_1_V_full_n(inputs_3_1_V_full_n);
    read_input_U0->inputs_3_1_V_write(read_input_U0_inputs_3_1_V_write);
    read_input_U0->inputs_3_2_V_din(read_input_U0_inputs_3_2_V_din);
    read_input_U0->inputs_3_2_V_full_n(inputs_3_2_V_full_n);
    read_input_U0->inputs_3_2_V_write(read_input_U0_inputs_3_2_V_write);
    kernel_U0 = new kernel("kernel_U0");
    kernel_U0->ap_clk(ap_clk);
    kernel_U0->ap_rst(ap_rst_n_inv);
    kernel_U0->ap_start(kernel_U0_ap_start);
    kernel_U0->start_full_n(start_for_write_output_U0_full_n);
    kernel_U0->ap_done(kernel_U0_ap_done);
    kernel_U0->ap_continue(kernel_U0_ap_continue);
    kernel_U0->ap_idle(kernel_U0_ap_idle);
    kernel_U0->ap_ready(kernel_U0_ap_ready);
    kernel_U0->start_out(kernel_U0_start_out);
    kernel_U0->start_write(kernel_U0_start_write);
    kernel_U0->inputs_0_0_V_dout(inputs_0_0_V_dout);
    kernel_U0->inputs_0_0_V_empty_n(inputs_0_0_V_empty_n);
    kernel_U0->inputs_0_0_V_read(kernel_U0_inputs_0_0_V_read);
    kernel_U0->inputs_0_1_V_dout(inputs_0_1_V_dout);
    kernel_U0->inputs_0_1_V_empty_n(inputs_0_1_V_empty_n);
    kernel_U0->inputs_0_1_V_read(kernel_U0_inputs_0_1_V_read);
    kernel_U0->inputs_0_2_V_dout(inputs_0_2_V_dout);
    kernel_U0->inputs_0_2_V_empty_n(inputs_0_2_V_empty_n);
    kernel_U0->inputs_0_2_V_read(kernel_U0_inputs_0_2_V_read);
    kernel_U0->inputs_1_0_V_dout(inputs_1_0_V_dout);
    kernel_U0->inputs_1_0_V_empty_n(inputs_1_0_V_empty_n);
    kernel_U0->inputs_1_0_V_read(kernel_U0_inputs_1_0_V_read);
    kernel_U0->inputs_1_1_V_dout(inputs_1_1_V_dout);
    kernel_U0->inputs_1_1_V_empty_n(inputs_1_1_V_empty_n);
    kernel_U0->inputs_1_1_V_read(kernel_U0_inputs_1_1_V_read);
    kernel_U0->inputs_1_2_V_dout(inputs_1_2_V_dout);
    kernel_U0->inputs_1_2_V_empty_n(inputs_1_2_V_empty_n);
    kernel_U0->inputs_1_2_V_read(kernel_U0_inputs_1_2_V_read);
    kernel_U0->inputs_2_0_V_dout(inputs_2_0_V_dout);
    kernel_U0->inputs_2_0_V_empty_n(inputs_2_0_V_empty_n);
    kernel_U0->inputs_2_0_V_read(kernel_U0_inputs_2_0_V_read);
    kernel_U0->inputs_2_1_V_dout(inputs_2_1_V_dout);
    kernel_U0->inputs_2_1_V_empty_n(inputs_2_1_V_empty_n);
    kernel_U0->inputs_2_1_V_read(kernel_U0_inputs_2_1_V_read);
    kernel_U0->inputs_2_2_V_dout(inputs_2_2_V_dout);
    kernel_U0->inputs_2_2_V_empty_n(inputs_2_2_V_empty_n);
    kernel_U0->inputs_2_2_V_read(kernel_U0_inputs_2_2_V_read);
    kernel_U0->inputs_3_0_V_dout(inputs_3_0_V_dout);
    kernel_U0->inputs_3_0_V_empty_n(inputs_3_0_V_empty_n);
    kernel_U0->inputs_3_0_V_read(kernel_U0_inputs_3_0_V_read);
    kernel_U0->inputs_3_1_V_dout(inputs_3_1_V_dout);
    kernel_U0->inputs_3_1_V_empty_n(inputs_3_1_V_empty_n);
    kernel_U0->inputs_3_1_V_read(kernel_U0_inputs_3_1_V_read);
    kernel_U0->inputs_3_2_V_dout(inputs_3_2_V_dout);
    kernel_U0->inputs_3_2_V_empty_n(inputs_3_2_V_empty_n);
    kernel_U0->inputs_3_2_V_read(kernel_U0_inputs_3_2_V_read);
    kernel_U0->outputs_0_0_V_din(kernel_U0_outputs_0_0_V_din);
    kernel_U0->outputs_0_0_V_full_n(outputs_0_0_V_full_n);
    kernel_U0->outputs_0_0_V_write(kernel_U0_outputs_0_0_V_write);
    kernel_U0->outputs_0_1_V_din(kernel_U0_outputs_0_1_V_din);
    kernel_U0->outputs_0_1_V_full_n(outputs_0_1_V_full_n);
    kernel_U0->outputs_0_1_V_write(kernel_U0_outputs_0_1_V_write);
    kernel_U0->outputs_0_2_V_din(kernel_U0_outputs_0_2_V_din);
    kernel_U0->outputs_0_2_V_full_n(outputs_0_2_V_full_n);
    kernel_U0->outputs_0_2_V_write(kernel_U0_outputs_0_2_V_write);
    kernel_U0->outputs_0_3_V_din(kernel_U0_outputs_0_3_V_din);
    kernel_U0->outputs_0_3_V_full_n(outputs_0_3_V_full_n);
    kernel_U0->outputs_0_3_V_write(kernel_U0_outputs_0_3_V_write);
    kernel_U0->outputs_1_0_V_din(kernel_U0_outputs_1_0_V_din);
    kernel_U0->outputs_1_0_V_full_n(outputs_1_0_V_full_n);
    kernel_U0->outputs_1_0_V_write(kernel_U0_outputs_1_0_V_write);
    kernel_U0->outputs_1_1_V_din(kernel_U0_outputs_1_1_V_din);
    kernel_U0->outputs_1_1_V_full_n(outputs_1_1_V_full_n);
    kernel_U0->outputs_1_1_V_write(kernel_U0_outputs_1_1_V_write);
    kernel_U0->outputs_1_2_V_din(kernel_U0_outputs_1_2_V_din);
    kernel_U0->outputs_1_2_V_full_n(outputs_1_2_V_full_n);
    kernel_U0->outputs_1_2_V_write(kernel_U0_outputs_1_2_V_write);
    kernel_U0->outputs_1_3_V_din(kernel_U0_outputs_1_3_V_din);
    kernel_U0->outputs_1_3_V_full_n(outputs_1_3_V_full_n);
    kernel_U0->outputs_1_3_V_write(kernel_U0_outputs_1_3_V_write);
    write_output_U0 = new write_output("write_output_U0");
    write_output_U0->ap_clk(ap_clk);
    write_output_U0->ap_rst(ap_rst_n_inv);
    write_output_U0->ap_start(write_output_U0_ap_start);
    write_output_U0->ap_done(write_output_U0_ap_done);
    write_output_U0->ap_continue(write_output_U0_ap_continue);
    write_output_U0->ap_idle(write_output_U0_ap_idle);
    write_output_U0->ap_ready(write_output_U0_ap_ready);
    write_output_U0->outputs_0_0_V_dout(outputs_0_0_V_dout);
    write_output_U0->outputs_0_0_V_empty_n(outputs_0_0_V_empty_n);
    write_output_U0->outputs_0_0_V_read(write_output_U0_outputs_0_0_V_read);
    write_output_U0->outputs_0_1_V_dout(outputs_0_1_V_dout);
    write_output_U0->outputs_0_1_V_empty_n(outputs_0_1_V_empty_n);
    write_output_U0->outputs_0_1_V_read(write_output_U0_outputs_0_1_V_read);
    write_output_U0->outputs_0_2_V_dout(outputs_0_2_V_dout);
    write_output_U0->outputs_0_2_V_empty_n(outputs_0_2_V_empty_n);
    write_output_U0->outputs_0_2_V_read(write_output_U0_outputs_0_2_V_read);
    write_output_U0->outputs_0_3_V_dout(outputs_0_3_V_dout);
    write_output_U0->outputs_0_3_V_empty_n(outputs_0_3_V_empty_n);
    write_output_U0->outputs_0_3_V_read(write_output_U0_outputs_0_3_V_read);
    write_output_U0->outputs_1_0_V_dout(outputs_1_0_V_dout);
    write_output_U0->outputs_1_0_V_empty_n(outputs_1_0_V_empty_n);
    write_output_U0->outputs_1_0_V_read(write_output_U0_outputs_1_0_V_read);
    write_output_U0->outputs_1_1_V_dout(outputs_1_1_V_dout);
    write_output_U0->outputs_1_1_V_empty_n(outputs_1_1_V_empty_n);
    write_output_U0->outputs_1_1_V_read(write_output_U0_outputs_1_1_V_read);
    write_output_U0->outputs_1_2_V_dout(outputs_1_2_V_dout);
    write_output_U0->outputs_1_2_V_empty_n(outputs_1_2_V_empty_n);
    write_output_U0->outputs_1_2_V_read(write_output_U0_outputs_1_2_V_read);
    write_output_U0->outputs_1_3_V_dout(outputs_1_3_V_dout);
    write_output_U0->outputs_1_3_V_empty_n(outputs_1_3_V_empty_n);
    write_output_U0->outputs_1_3_V_read(write_output_U0_outputs_1_3_V_read);
    write_output_U0->out_0_TDATA(write_output_U0_out_0_TDATA);
    write_output_U0->out_0_TVALID(write_output_U0_out_0_TVALID);
    write_output_U0->out_0_TREADY(out_0_TREADY);
    write_output_U0->out_1_TDATA(write_output_U0_out_1_TDATA);
    write_output_U0->out_1_TVALID(write_output_U0_out_1_TVALID);
    write_output_U0->out_1_TREADY(out_1_TREADY);
    write_output_U0->out_0_TKEEP(write_output_U0_out_0_TKEEP);
    write_output_U0->out_1_TKEEP(write_output_U0_out_1_TKEEP);
    write_output_U0->out_0_TSTRB(write_output_U0_out_0_TSTRB);
    write_output_U0->out_1_TSTRB(write_output_U0_out_1_TSTRB);
    write_output_U0->out_0_TLAST(write_output_U0_out_0_TLAST);
    write_output_U0->out_1_TLAST(write_output_U0_out_1_TLAST);
    inputs_0_0_V_U = new fifo_w8_d8_A("inputs_0_0_V_U");
    inputs_0_0_V_U->clk(ap_clk);
    inputs_0_0_V_U->reset(ap_rst_n_inv);
    inputs_0_0_V_U->if_read_ce(ap_var_for_const0);
    inputs_0_0_V_U->if_write_ce(ap_var_for_const0);
    inputs_0_0_V_U->if_din(read_input_U0_inputs_0_0_V_din);
    inputs_0_0_V_U->if_full_n(inputs_0_0_V_full_n);
    inputs_0_0_V_U->if_write(read_input_U0_inputs_0_0_V_write);
    inputs_0_0_V_U->if_dout(inputs_0_0_V_dout);
    inputs_0_0_V_U->if_empty_n(inputs_0_0_V_empty_n);
    inputs_0_0_V_U->if_read(kernel_U0_inputs_0_0_V_read);
    inputs_0_1_V_U = new fifo_w8_d8_A("inputs_0_1_V_U");
    inputs_0_1_V_U->clk(ap_clk);
    inputs_0_1_V_U->reset(ap_rst_n_inv);
    inputs_0_1_V_U->if_read_ce(ap_var_for_const0);
    inputs_0_1_V_U->if_write_ce(ap_var_for_const0);
    inputs_0_1_V_U->if_din(read_input_U0_inputs_0_1_V_din);
    inputs_0_1_V_U->if_full_n(inputs_0_1_V_full_n);
    inputs_0_1_V_U->if_write(read_input_U0_inputs_0_1_V_write);
    inputs_0_1_V_U->if_dout(inputs_0_1_V_dout);
    inputs_0_1_V_U->if_empty_n(inputs_0_1_V_empty_n);
    inputs_0_1_V_U->if_read(kernel_U0_inputs_0_1_V_read);
    inputs_0_2_V_U = new fifo_w8_d8_A("inputs_0_2_V_U");
    inputs_0_2_V_U->clk(ap_clk);
    inputs_0_2_V_U->reset(ap_rst_n_inv);
    inputs_0_2_V_U->if_read_ce(ap_var_for_const0);
    inputs_0_2_V_U->if_write_ce(ap_var_for_const0);
    inputs_0_2_V_U->if_din(read_input_U0_inputs_0_2_V_din);
    inputs_0_2_V_U->if_full_n(inputs_0_2_V_full_n);
    inputs_0_2_V_U->if_write(read_input_U0_inputs_0_2_V_write);
    inputs_0_2_V_U->if_dout(inputs_0_2_V_dout);
    inputs_0_2_V_U->if_empty_n(inputs_0_2_V_empty_n);
    inputs_0_2_V_U->if_read(kernel_U0_inputs_0_2_V_read);
    inputs_1_0_V_U = new fifo_w8_d8_A("inputs_1_0_V_U");
    inputs_1_0_V_U->clk(ap_clk);
    inputs_1_0_V_U->reset(ap_rst_n_inv);
    inputs_1_0_V_U->if_read_ce(ap_var_for_const0);
    inputs_1_0_V_U->if_write_ce(ap_var_for_const0);
    inputs_1_0_V_U->if_din(read_input_U0_inputs_1_0_V_din);
    inputs_1_0_V_U->if_full_n(inputs_1_0_V_full_n);
    inputs_1_0_V_U->if_write(read_input_U0_inputs_1_0_V_write);
    inputs_1_0_V_U->if_dout(inputs_1_0_V_dout);
    inputs_1_0_V_U->if_empty_n(inputs_1_0_V_empty_n);
    inputs_1_0_V_U->if_read(kernel_U0_inputs_1_0_V_read);
    inputs_1_1_V_U = new fifo_w8_d8_A("inputs_1_1_V_U");
    inputs_1_1_V_U->clk(ap_clk);
    inputs_1_1_V_U->reset(ap_rst_n_inv);
    inputs_1_1_V_U->if_read_ce(ap_var_for_const0);
    inputs_1_1_V_U->if_write_ce(ap_var_for_const0);
    inputs_1_1_V_U->if_din(read_input_U0_inputs_1_1_V_din);
    inputs_1_1_V_U->if_full_n(inputs_1_1_V_full_n);
    inputs_1_1_V_U->if_write(read_input_U0_inputs_1_1_V_write);
    inputs_1_1_V_U->if_dout(inputs_1_1_V_dout);
    inputs_1_1_V_U->if_empty_n(inputs_1_1_V_empty_n);
    inputs_1_1_V_U->if_read(kernel_U0_inputs_1_1_V_read);
    inputs_1_2_V_U = new fifo_w8_d8_A("inputs_1_2_V_U");
    inputs_1_2_V_U->clk(ap_clk);
    inputs_1_2_V_U->reset(ap_rst_n_inv);
    inputs_1_2_V_U->if_read_ce(ap_var_for_const0);
    inputs_1_2_V_U->if_write_ce(ap_var_for_const0);
    inputs_1_2_V_U->if_din(read_input_U0_inputs_1_2_V_din);
    inputs_1_2_V_U->if_full_n(inputs_1_2_V_full_n);
    inputs_1_2_V_U->if_write(read_input_U0_inputs_1_2_V_write);
    inputs_1_2_V_U->if_dout(inputs_1_2_V_dout);
    inputs_1_2_V_U->if_empty_n(inputs_1_2_V_empty_n);
    inputs_1_2_V_U->if_read(kernel_U0_inputs_1_2_V_read);
    inputs_2_0_V_U = new fifo_w8_d8_A("inputs_2_0_V_U");
    inputs_2_0_V_U->clk(ap_clk);
    inputs_2_0_V_U->reset(ap_rst_n_inv);
    inputs_2_0_V_U->if_read_ce(ap_var_for_const0);
    inputs_2_0_V_U->if_write_ce(ap_var_for_const0);
    inputs_2_0_V_U->if_din(read_input_U0_inputs_2_0_V_din);
    inputs_2_0_V_U->if_full_n(inputs_2_0_V_full_n);
    inputs_2_0_V_U->if_write(read_input_U0_inputs_2_0_V_write);
    inputs_2_0_V_U->if_dout(inputs_2_0_V_dout);
    inputs_2_0_V_U->if_empty_n(inputs_2_0_V_empty_n);
    inputs_2_0_V_U->if_read(kernel_U0_inputs_2_0_V_read);
    inputs_2_1_V_U = new fifo_w8_d8_A("inputs_2_1_V_U");
    inputs_2_1_V_U->clk(ap_clk);
    inputs_2_1_V_U->reset(ap_rst_n_inv);
    inputs_2_1_V_U->if_read_ce(ap_var_for_const0);
    inputs_2_1_V_U->if_write_ce(ap_var_for_const0);
    inputs_2_1_V_U->if_din(read_input_U0_inputs_2_1_V_din);
    inputs_2_1_V_U->if_full_n(inputs_2_1_V_full_n);
    inputs_2_1_V_U->if_write(read_input_U0_inputs_2_1_V_write);
    inputs_2_1_V_U->if_dout(inputs_2_1_V_dout);
    inputs_2_1_V_U->if_empty_n(inputs_2_1_V_empty_n);
    inputs_2_1_V_U->if_read(kernel_U0_inputs_2_1_V_read);
    inputs_2_2_V_U = new fifo_w8_d8_A("inputs_2_2_V_U");
    inputs_2_2_V_U->clk(ap_clk);
    inputs_2_2_V_U->reset(ap_rst_n_inv);
    inputs_2_2_V_U->if_read_ce(ap_var_for_const0);
    inputs_2_2_V_U->if_write_ce(ap_var_for_const0);
    inputs_2_2_V_U->if_din(read_input_U0_inputs_2_2_V_din);
    inputs_2_2_V_U->if_full_n(inputs_2_2_V_full_n);
    inputs_2_2_V_U->if_write(read_input_U0_inputs_2_2_V_write);
    inputs_2_2_V_U->if_dout(inputs_2_2_V_dout);
    inputs_2_2_V_U->if_empty_n(inputs_2_2_V_empty_n);
    inputs_2_2_V_U->if_read(kernel_U0_inputs_2_2_V_read);
    inputs_3_0_V_U = new fifo_w8_d8_A("inputs_3_0_V_U");
    inputs_3_0_V_U->clk(ap_clk);
    inputs_3_0_V_U->reset(ap_rst_n_inv);
    inputs_3_0_V_U->if_read_ce(ap_var_for_const0);
    inputs_3_0_V_U->if_write_ce(ap_var_for_const0);
    inputs_3_0_V_U->if_din(read_input_U0_inputs_3_0_V_din);
    inputs_3_0_V_U->if_full_n(inputs_3_0_V_full_n);
    inputs_3_0_V_U->if_write(read_input_U0_inputs_3_0_V_write);
    inputs_3_0_V_U->if_dout(inputs_3_0_V_dout);
    inputs_3_0_V_U->if_empty_n(inputs_3_0_V_empty_n);
    inputs_3_0_V_U->if_read(kernel_U0_inputs_3_0_V_read);
    inputs_3_1_V_U = new fifo_w8_d8_A("inputs_3_1_V_U");
    inputs_3_1_V_U->clk(ap_clk);
    inputs_3_1_V_U->reset(ap_rst_n_inv);
    inputs_3_1_V_U->if_read_ce(ap_var_for_const0);
    inputs_3_1_V_U->if_write_ce(ap_var_for_const0);
    inputs_3_1_V_U->if_din(read_input_U0_inputs_3_1_V_din);
    inputs_3_1_V_U->if_full_n(inputs_3_1_V_full_n);
    inputs_3_1_V_U->if_write(read_input_U0_inputs_3_1_V_write);
    inputs_3_1_V_U->if_dout(inputs_3_1_V_dout);
    inputs_3_1_V_U->if_empty_n(inputs_3_1_V_empty_n);
    inputs_3_1_V_U->if_read(kernel_U0_inputs_3_1_V_read);
    inputs_3_2_V_U = new fifo_w8_d8_A("inputs_3_2_V_U");
    inputs_3_2_V_U->clk(ap_clk);
    inputs_3_2_V_U->reset(ap_rst_n_inv);
    inputs_3_2_V_U->if_read_ce(ap_var_for_const0);
    inputs_3_2_V_U->if_write_ce(ap_var_for_const0);
    inputs_3_2_V_U->if_din(read_input_U0_inputs_3_2_V_din);
    inputs_3_2_V_U->if_full_n(inputs_3_2_V_full_n);
    inputs_3_2_V_U->if_write(read_input_U0_inputs_3_2_V_write);
    inputs_3_2_V_U->if_dout(inputs_3_2_V_dout);
    inputs_3_2_V_U->if_empty_n(inputs_3_2_V_empty_n);
    inputs_3_2_V_U->if_read(kernel_U0_inputs_3_2_V_read);
    outputs_0_0_V_U = new fifo_w16_d4_A("outputs_0_0_V_U");
    outputs_0_0_V_U->clk(ap_clk);
    outputs_0_0_V_U->reset(ap_rst_n_inv);
    outputs_0_0_V_U->if_read_ce(ap_var_for_const0);
    outputs_0_0_V_U->if_write_ce(ap_var_for_const0);
    outputs_0_0_V_U->if_din(kernel_U0_outputs_0_0_V_din);
    outputs_0_0_V_U->if_full_n(outputs_0_0_V_full_n);
    outputs_0_0_V_U->if_write(kernel_U0_outputs_0_0_V_write);
    outputs_0_0_V_U->if_dout(outputs_0_0_V_dout);
    outputs_0_0_V_U->if_empty_n(outputs_0_0_V_empty_n);
    outputs_0_0_V_U->if_read(write_output_U0_outputs_0_0_V_read);
    outputs_0_1_V_U = new fifo_w16_d4_A("outputs_0_1_V_U");
    outputs_0_1_V_U->clk(ap_clk);
    outputs_0_1_V_U->reset(ap_rst_n_inv);
    outputs_0_1_V_U->if_read_ce(ap_var_for_const0);
    outputs_0_1_V_U->if_write_ce(ap_var_for_const0);
    outputs_0_1_V_U->if_din(kernel_U0_outputs_0_1_V_din);
    outputs_0_1_V_U->if_full_n(outputs_0_1_V_full_n);
    outputs_0_1_V_U->if_write(kernel_U0_outputs_0_1_V_write);
    outputs_0_1_V_U->if_dout(outputs_0_1_V_dout);
    outputs_0_1_V_U->if_empty_n(outputs_0_1_V_empty_n);
    outputs_0_1_V_U->if_read(write_output_U0_outputs_0_1_V_read);
    outputs_0_2_V_U = new fifo_w16_d4_A("outputs_0_2_V_U");
    outputs_0_2_V_U->clk(ap_clk);
    outputs_0_2_V_U->reset(ap_rst_n_inv);
    outputs_0_2_V_U->if_read_ce(ap_var_for_const0);
    outputs_0_2_V_U->if_write_ce(ap_var_for_const0);
    outputs_0_2_V_U->if_din(kernel_U0_outputs_0_2_V_din);
    outputs_0_2_V_U->if_full_n(outputs_0_2_V_full_n);
    outputs_0_2_V_U->if_write(kernel_U0_outputs_0_2_V_write);
    outputs_0_2_V_U->if_dout(outputs_0_2_V_dout);
    outputs_0_2_V_U->if_empty_n(outputs_0_2_V_empty_n);
    outputs_0_2_V_U->if_read(write_output_U0_outputs_0_2_V_read);
    outputs_0_3_V_U = new fifo_w16_d4_A("outputs_0_3_V_U");
    outputs_0_3_V_U->clk(ap_clk);
    outputs_0_3_V_U->reset(ap_rst_n_inv);
    outputs_0_3_V_U->if_read_ce(ap_var_for_const0);
    outputs_0_3_V_U->if_write_ce(ap_var_for_const0);
    outputs_0_3_V_U->if_din(kernel_U0_outputs_0_3_V_din);
    outputs_0_3_V_U->if_full_n(outputs_0_3_V_full_n);
    outputs_0_3_V_U->if_write(kernel_U0_outputs_0_3_V_write);
    outputs_0_3_V_U->if_dout(outputs_0_3_V_dout);
    outputs_0_3_V_U->if_empty_n(outputs_0_3_V_empty_n);
    outputs_0_3_V_U->if_read(write_output_U0_outputs_0_3_V_read);
    outputs_1_0_V_U = new fifo_w16_d4_A("outputs_1_0_V_U");
    outputs_1_0_V_U->clk(ap_clk);
    outputs_1_0_V_U->reset(ap_rst_n_inv);
    outputs_1_0_V_U->if_read_ce(ap_var_for_const0);
    outputs_1_0_V_U->if_write_ce(ap_var_for_const0);
    outputs_1_0_V_U->if_din(kernel_U0_outputs_1_0_V_din);
    outputs_1_0_V_U->if_full_n(outputs_1_0_V_full_n);
    outputs_1_0_V_U->if_write(kernel_U0_outputs_1_0_V_write);
    outputs_1_0_V_U->if_dout(outputs_1_0_V_dout);
    outputs_1_0_V_U->if_empty_n(outputs_1_0_V_empty_n);
    outputs_1_0_V_U->if_read(write_output_U0_outputs_1_0_V_read);
    outputs_1_1_V_U = new fifo_w16_d4_A("outputs_1_1_V_U");
    outputs_1_1_V_U->clk(ap_clk);
    outputs_1_1_V_U->reset(ap_rst_n_inv);
    outputs_1_1_V_U->if_read_ce(ap_var_for_const0);
    outputs_1_1_V_U->if_write_ce(ap_var_for_const0);
    outputs_1_1_V_U->if_din(kernel_U0_outputs_1_1_V_din);
    outputs_1_1_V_U->if_full_n(outputs_1_1_V_full_n);
    outputs_1_1_V_U->if_write(kernel_U0_outputs_1_1_V_write);
    outputs_1_1_V_U->if_dout(outputs_1_1_V_dout);
    outputs_1_1_V_U->if_empty_n(outputs_1_1_V_empty_n);
    outputs_1_1_V_U->if_read(write_output_U0_outputs_1_1_V_read);
    outputs_1_2_V_U = new fifo_w16_d4_A("outputs_1_2_V_U");
    outputs_1_2_V_U->clk(ap_clk);
    outputs_1_2_V_U->reset(ap_rst_n_inv);
    outputs_1_2_V_U->if_read_ce(ap_var_for_const0);
    outputs_1_2_V_U->if_write_ce(ap_var_for_const0);
    outputs_1_2_V_U->if_din(kernel_U0_outputs_1_2_V_din);
    outputs_1_2_V_U->if_full_n(outputs_1_2_V_full_n);
    outputs_1_2_V_U->if_write(kernel_U0_outputs_1_2_V_write);
    outputs_1_2_V_U->if_dout(outputs_1_2_V_dout);
    outputs_1_2_V_U->if_empty_n(outputs_1_2_V_empty_n);
    outputs_1_2_V_U->if_read(write_output_U0_outputs_1_2_V_read);
    outputs_1_3_V_U = new fifo_w16_d4_A("outputs_1_3_V_U");
    outputs_1_3_V_U->clk(ap_clk);
    outputs_1_3_V_U->reset(ap_rst_n_inv);
    outputs_1_3_V_U->if_read_ce(ap_var_for_const0);
    outputs_1_3_V_U->if_write_ce(ap_var_for_const0);
    outputs_1_3_V_U->if_din(kernel_U0_outputs_1_3_V_din);
    outputs_1_3_V_U->if_full_n(outputs_1_3_V_full_n);
    outputs_1_3_V_U->if_write(kernel_U0_outputs_1_3_V_write);
    outputs_1_3_V_U->if_dout(outputs_1_3_V_dout);
    outputs_1_3_V_U->if_empty_n(outputs_1_3_V_empty_n);
    outputs_1_3_V_U->if_read(write_output_U0_outputs_1_3_V_read);
    start_for_kernel_U0_U = new start_for_kernel_U0("start_for_kernel_U0_U");
    start_for_kernel_U0_U->clk(ap_clk);
    start_for_kernel_U0_U->reset(ap_rst_n_inv);
    start_for_kernel_U0_U->if_read_ce(ap_var_for_const0);
    start_for_kernel_U0_U->if_write_ce(ap_var_for_const0);
    start_for_kernel_U0_U->if_din(start_for_kernel_U0_din);
    start_for_kernel_U0_U->if_full_n(start_for_kernel_U0_full_n);
    start_for_kernel_U0_U->if_write(read_input_U0_start_write);
    start_for_kernel_U0_U->if_dout(start_for_kernel_U0_dout);
    start_for_kernel_U0_U->if_empty_n(start_for_kernel_U0_empty_n);
    start_for_kernel_U0_U->if_read(kernel_U0_ap_ready);
    start_for_write_ofYi_U = new start_for_write_ofYi("start_for_write_ofYi_U");
    start_for_write_ofYi_U->clk(ap_clk);
    start_for_write_ofYi_U->reset(ap_rst_n_inv);
    start_for_write_ofYi_U->if_read_ce(ap_var_for_const0);
    start_for_write_ofYi_U->if_write_ce(ap_var_for_const0);
    start_for_write_ofYi_U->if_din(start_for_write_output_U0_din);
    start_for_write_ofYi_U->if_full_n(start_for_write_output_U0_full_n);
    start_for_write_ofYi_U->if_write(kernel_U0_start_write);
    start_for_write_ofYi_U->if_dout(start_for_write_output_U0_dout);
    start_for_write_ofYi_U->if_empty_n(start_for_write_output_U0_empty_n);
    start_for_write_ofYi_U->if_read(write_output_U0_ap_ready);

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_in_0_TREADY);
    sensitive << ( read_input_U0_in_0_TREADY );

    SC_METHOD(thread_in_1_TREADY);
    sensitive << ( read_input_U0_in_1_TREADY );

    SC_METHOD(thread_in_2_TREADY);
    sensitive << ( read_input_U0_in_2_TREADY );

    SC_METHOD(thread_in_3_TREADY);
    sensitive << ( read_input_U0_in_3_TREADY );

    SC_METHOD(thread_kernel_U0_ap_continue);

    SC_METHOD(thread_kernel_U0_ap_start);
    sensitive << ( start_for_kernel_U0_empty_n );

    SC_METHOD(thread_out_0_TDATA);
    sensitive << ( write_output_U0_out_0_TDATA );

    SC_METHOD(thread_out_0_TKEEP);
    sensitive << ( write_output_U0_out_0_TKEEP );

    SC_METHOD(thread_out_0_TLAST);
    sensitive << ( write_output_U0_out_0_TLAST );

    SC_METHOD(thread_out_0_TSTRB);
    sensitive << ( write_output_U0_out_0_TSTRB );

    SC_METHOD(thread_out_0_TVALID);
    sensitive << ( write_output_U0_out_0_TVALID );

    SC_METHOD(thread_out_1_TDATA);
    sensitive << ( write_output_U0_out_1_TDATA );

    SC_METHOD(thread_out_1_TKEEP);
    sensitive << ( write_output_U0_out_1_TKEEP );

    SC_METHOD(thread_out_1_TLAST);
    sensitive << ( write_output_U0_out_1_TLAST );

    SC_METHOD(thread_out_1_TSTRB);
    sensitive << ( write_output_U0_out_1_TSTRB );

    SC_METHOD(thread_out_1_TVALID);
    sensitive << ( write_output_U0_out_1_TVALID );

    SC_METHOD(thread_read_input_U0_ap_continue);

    SC_METHOD(thread_read_input_U0_ap_start);

    SC_METHOD(thread_start_for_kernel_U0_din);

    SC_METHOD(thread_start_for_write_output_U0_din);

    SC_METHOD(thread_write_output_U0_ap_continue);

    SC_METHOD(thread_write_output_U0_ap_start);
    sensitive << ( start_for_write_output_U0_empty_n );

    SC_METHOD(thread_write_output_U0_start_full_n);

    SC_METHOD(thread_write_output_U0_start_write);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cnn_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, in_0_TDATA, "(port)in_0_TDATA");
    sc_trace(mVcdFile, in_1_TDATA, "(port)in_1_TDATA");
    sc_trace(mVcdFile, in_2_TDATA, "(port)in_2_TDATA");
    sc_trace(mVcdFile, in_3_TDATA, "(port)in_3_TDATA");
    sc_trace(mVcdFile, in_0_TKEEP, "(port)in_0_TKEEP");
    sc_trace(mVcdFile, in_1_TKEEP, "(port)in_1_TKEEP");
    sc_trace(mVcdFile, in_2_TKEEP, "(port)in_2_TKEEP");
    sc_trace(mVcdFile, in_3_TKEEP, "(port)in_3_TKEEP");
    sc_trace(mVcdFile, in_0_TSTRB, "(port)in_0_TSTRB");
    sc_trace(mVcdFile, in_1_TSTRB, "(port)in_1_TSTRB");
    sc_trace(mVcdFile, in_2_TSTRB, "(port)in_2_TSTRB");
    sc_trace(mVcdFile, in_3_TSTRB, "(port)in_3_TSTRB");
    sc_trace(mVcdFile, in_0_TLAST, "(port)in_0_TLAST");
    sc_trace(mVcdFile, in_1_TLAST, "(port)in_1_TLAST");
    sc_trace(mVcdFile, in_2_TLAST, "(port)in_2_TLAST");
    sc_trace(mVcdFile, in_3_TLAST, "(port)in_3_TLAST");
    sc_trace(mVcdFile, out_0_TDATA, "(port)out_0_TDATA");
    sc_trace(mVcdFile, out_1_TDATA, "(port)out_1_TDATA");
    sc_trace(mVcdFile, out_0_TKEEP, "(port)out_0_TKEEP");
    sc_trace(mVcdFile, out_1_TKEEP, "(port)out_1_TKEEP");
    sc_trace(mVcdFile, out_0_TSTRB, "(port)out_0_TSTRB");
    sc_trace(mVcdFile, out_1_TSTRB, "(port)out_1_TSTRB");
    sc_trace(mVcdFile, out_0_TLAST, "(port)out_0_TLAST");
    sc_trace(mVcdFile, out_1_TLAST, "(port)out_1_TLAST");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, in_0_TVALID, "(port)in_0_TVALID");
    sc_trace(mVcdFile, in_0_TREADY, "(port)in_0_TREADY");
    sc_trace(mVcdFile, in_1_TVALID, "(port)in_1_TVALID");
    sc_trace(mVcdFile, in_1_TREADY, "(port)in_1_TREADY");
    sc_trace(mVcdFile, in_2_TVALID, "(port)in_2_TVALID");
    sc_trace(mVcdFile, in_2_TREADY, "(port)in_2_TREADY");
    sc_trace(mVcdFile, in_3_TVALID, "(port)in_3_TVALID");
    sc_trace(mVcdFile, in_3_TREADY, "(port)in_3_TREADY");
    sc_trace(mVcdFile, out_0_TVALID, "(port)out_0_TVALID");
    sc_trace(mVcdFile, out_0_TREADY, "(port)out_0_TREADY");
    sc_trace(mVcdFile, out_1_TVALID, "(port)out_1_TVALID");
    sc_trace(mVcdFile, out_1_TREADY, "(port)out_1_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, read_input_U0_ap_start, "read_input_U0_ap_start");
    sc_trace(mVcdFile, read_input_U0_ap_done, "read_input_U0_ap_done");
    sc_trace(mVcdFile, read_input_U0_ap_continue, "read_input_U0_ap_continue");
    sc_trace(mVcdFile, read_input_U0_ap_idle, "read_input_U0_ap_idle");
    sc_trace(mVcdFile, read_input_U0_ap_ready, "read_input_U0_ap_ready");
    sc_trace(mVcdFile, read_input_U0_start_out, "read_input_U0_start_out");
    sc_trace(mVcdFile, read_input_U0_start_write, "read_input_U0_start_write");
    sc_trace(mVcdFile, read_input_U0_in_0_TREADY, "read_input_U0_in_0_TREADY");
    sc_trace(mVcdFile, read_input_U0_in_1_TREADY, "read_input_U0_in_1_TREADY");
    sc_trace(mVcdFile, read_input_U0_in_2_TREADY, "read_input_U0_in_2_TREADY");
    sc_trace(mVcdFile, read_input_U0_in_3_TREADY, "read_input_U0_in_3_TREADY");
    sc_trace(mVcdFile, read_input_U0_inputs_0_0_V_din, "read_input_U0_inputs_0_0_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_0_0_V_write, "read_input_U0_inputs_0_0_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_0_1_V_din, "read_input_U0_inputs_0_1_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_0_1_V_write, "read_input_U0_inputs_0_1_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_0_2_V_din, "read_input_U0_inputs_0_2_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_0_2_V_write, "read_input_U0_inputs_0_2_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_1_0_V_din, "read_input_U0_inputs_1_0_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_1_0_V_write, "read_input_U0_inputs_1_0_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_1_1_V_din, "read_input_U0_inputs_1_1_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_1_1_V_write, "read_input_U0_inputs_1_1_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_1_2_V_din, "read_input_U0_inputs_1_2_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_1_2_V_write, "read_input_U0_inputs_1_2_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_2_0_V_din, "read_input_U0_inputs_2_0_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_2_0_V_write, "read_input_U0_inputs_2_0_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_2_1_V_din, "read_input_U0_inputs_2_1_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_2_1_V_write, "read_input_U0_inputs_2_1_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_2_2_V_din, "read_input_U0_inputs_2_2_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_2_2_V_write, "read_input_U0_inputs_2_2_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_3_0_V_din, "read_input_U0_inputs_3_0_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_3_0_V_write, "read_input_U0_inputs_3_0_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_3_1_V_din, "read_input_U0_inputs_3_1_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_3_1_V_write, "read_input_U0_inputs_3_1_V_write");
    sc_trace(mVcdFile, read_input_U0_inputs_3_2_V_din, "read_input_U0_inputs_3_2_V_din");
    sc_trace(mVcdFile, read_input_U0_inputs_3_2_V_write, "read_input_U0_inputs_3_2_V_write");
    sc_trace(mVcdFile, kernel_U0_ap_start, "kernel_U0_ap_start");
    sc_trace(mVcdFile, kernel_U0_ap_done, "kernel_U0_ap_done");
    sc_trace(mVcdFile, kernel_U0_ap_continue, "kernel_U0_ap_continue");
    sc_trace(mVcdFile, kernel_U0_ap_idle, "kernel_U0_ap_idle");
    sc_trace(mVcdFile, kernel_U0_ap_ready, "kernel_U0_ap_ready");
    sc_trace(mVcdFile, kernel_U0_start_out, "kernel_U0_start_out");
    sc_trace(mVcdFile, kernel_U0_start_write, "kernel_U0_start_write");
    sc_trace(mVcdFile, kernel_U0_inputs_0_0_V_read, "kernel_U0_inputs_0_0_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_0_1_V_read, "kernel_U0_inputs_0_1_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_0_2_V_read, "kernel_U0_inputs_0_2_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_1_0_V_read, "kernel_U0_inputs_1_0_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_1_1_V_read, "kernel_U0_inputs_1_1_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_1_2_V_read, "kernel_U0_inputs_1_2_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_2_0_V_read, "kernel_U0_inputs_2_0_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_2_1_V_read, "kernel_U0_inputs_2_1_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_2_2_V_read, "kernel_U0_inputs_2_2_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_3_0_V_read, "kernel_U0_inputs_3_0_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_3_1_V_read, "kernel_U0_inputs_3_1_V_read");
    sc_trace(mVcdFile, kernel_U0_inputs_3_2_V_read, "kernel_U0_inputs_3_2_V_read");
    sc_trace(mVcdFile, kernel_U0_outputs_0_0_V_din, "kernel_U0_outputs_0_0_V_din");
    sc_trace(mVcdFile, kernel_U0_outputs_0_0_V_write, "kernel_U0_outputs_0_0_V_write");
    sc_trace(mVcdFile, kernel_U0_outputs_0_1_V_din, "kernel_U0_outputs_0_1_V_din");
    sc_trace(mVcdFile, kernel_U0_outputs_0_1_V_write, "kernel_U0_outputs_0_1_V_write");
    sc_trace(mVcdFile, kernel_U0_outputs_0_2_V_din, "kernel_U0_outputs_0_2_V_din");
    sc_trace(mVcdFile, kernel_U0_outputs_0_2_V_write, "kernel_U0_outputs_0_2_V_write");
    sc_trace(mVcdFile, kernel_U0_outputs_0_3_V_din, "kernel_U0_outputs_0_3_V_din");
    sc_trace(mVcdFile, kernel_U0_outputs_0_3_V_write, "kernel_U0_outputs_0_3_V_write");
    sc_trace(mVcdFile, kernel_U0_outputs_1_0_V_din, "kernel_U0_outputs_1_0_V_din");
    sc_trace(mVcdFile, kernel_U0_outputs_1_0_V_write, "kernel_U0_outputs_1_0_V_write");
    sc_trace(mVcdFile, kernel_U0_outputs_1_1_V_din, "kernel_U0_outputs_1_1_V_din");
    sc_trace(mVcdFile, kernel_U0_outputs_1_1_V_write, "kernel_U0_outputs_1_1_V_write");
    sc_trace(mVcdFile, kernel_U0_outputs_1_2_V_din, "kernel_U0_outputs_1_2_V_din");
    sc_trace(mVcdFile, kernel_U0_outputs_1_2_V_write, "kernel_U0_outputs_1_2_V_write");
    sc_trace(mVcdFile, kernel_U0_outputs_1_3_V_din, "kernel_U0_outputs_1_3_V_din");
    sc_trace(mVcdFile, kernel_U0_outputs_1_3_V_write, "kernel_U0_outputs_1_3_V_write");
    sc_trace(mVcdFile, write_output_U0_ap_start, "write_output_U0_ap_start");
    sc_trace(mVcdFile, write_output_U0_ap_done, "write_output_U0_ap_done");
    sc_trace(mVcdFile, write_output_U0_ap_continue, "write_output_U0_ap_continue");
    sc_trace(mVcdFile, write_output_U0_ap_idle, "write_output_U0_ap_idle");
    sc_trace(mVcdFile, write_output_U0_ap_ready, "write_output_U0_ap_ready");
    sc_trace(mVcdFile, write_output_U0_outputs_0_0_V_read, "write_output_U0_outputs_0_0_V_read");
    sc_trace(mVcdFile, write_output_U0_outputs_0_1_V_read, "write_output_U0_outputs_0_1_V_read");
    sc_trace(mVcdFile, write_output_U0_outputs_0_2_V_read, "write_output_U0_outputs_0_2_V_read");
    sc_trace(mVcdFile, write_output_U0_outputs_0_3_V_read, "write_output_U0_outputs_0_3_V_read");
    sc_trace(mVcdFile, write_output_U0_outputs_1_0_V_read, "write_output_U0_outputs_1_0_V_read");
    sc_trace(mVcdFile, write_output_U0_outputs_1_1_V_read, "write_output_U0_outputs_1_1_V_read");
    sc_trace(mVcdFile, write_output_U0_outputs_1_2_V_read, "write_output_U0_outputs_1_2_V_read");
    sc_trace(mVcdFile, write_output_U0_outputs_1_3_V_read, "write_output_U0_outputs_1_3_V_read");
    sc_trace(mVcdFile, write_output_U0_out_0_TDATA, "write_output_U0_out_0_TDATA");
    sc_trace(mVcdFile, write_output_U0_out_0_TVALID, "write_output_U0_out_0_TVALID");
    sc_trace(mVcdFile, write_output_U0_out_1_TDATA, "write_output_U0_out_1_TDATA");
    sc_trace(mVcdFile, write_output_U0_out_1_TVALID, "write_output_U0_out_1_TVALID");
    sc_trace(mVcdFile, write_output_U0_out_0_TKEEP, "write_output_U0_out_0_TKEEP");
    sc_trace(mVcdFile, write_output_U0_out_1_TKEEP, "write_output_U0_out_1_TKEEP");
    sc_trace(mVcdFile, write_output_U0_out_0_TSTRB, "write_output_U0_out_0_TSTRB");
    sc_trace(mVcdFile, write_output_U0_out_1_TSTRB, "write_output_U0_out_1_TSTRB");
    sc_trace(mVcdFile, write_output_U0_out_0_TLAST, "write_output_U0_out_0_TLAST");
    sc_trace(mVcdFile, write_output_U0_out_1_TLAST, "write_output_U0_out_1_TLAST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, inputs_0_0_V_full_n, "inputs_0_0_V_full_n");
    sc_trace(mVcdFile, inputs_0_0_V_dout, "inputs_0_0_V_dout");
    sc_trace(mVcdFile, inputs_0_0_V_empty_n, "inputs_0_0_V_empty_n");
    sc_trace(mVcdFile, inputs_0_1_V_full_n, "inputs_0_1_V_full_n");
    sc_trace(mVcdFile, inputs_0_1_V_dout, "inputs_0_1_V_dout");
    sc_trace(mVcdFile, inputs_0_1_V_empty_n, "inputs_0_1_V_empty_n");
    sc_trace(mVcdFile, inputs_0_2_V_full_n, "inputs_0_2_V_full_n");
    sc_trace(mVcdFile, inputs_0_2_V_dout, "inputs_0_2_V_dout");
    sc_trace(mVcdFile, inputs_0_2_V_empty_n, "inputs_0_2_V_empty_n");
    sc_trace(mVcdFile, inputs_1_0_V_full_n, "inputs_1_0_V_full_n");
    sc_trace(mVcdFile, inputs_1_0_V_dout, "inputs_1_0_V_dout");
    sc_trace(mVcdFile, inputs_1_0_V_empty_n, "inputs_1_0_V_empty_n");
    sc_trace(mVcdFile, inputs_1_1_V_full_n, "inputs_1_1_V_full_n");
    sc_trace(mVcdFile, inputs_1_1_V_dout, "inputs_1_1_V_dout");
    sc_trace(mVcdFile, inputs_1_1_V_empty_n, "inputs_1_1_V_empty_n");
    sc_trace(mVcdFile, inputs_1_2_V_full_n, "inputs_1_2_V_full_n");
    sc_trace(mVcdFile, inputs_1_2_V_dout, "inputs_1_2_V_dout");
    sc_trace(mVcdFile, inputs_1_2_V_empty_n, "inputs_1_2_V_empty_n");
    sc_trace(mVcdFile, inputs_2_0_V_full_n, "inputs_2_0_V_full_n");
    sc_trace(mVcdFile, inputs_2_0_V_dout, "inputs_2_0_V_dout");
    sc_trace(mVcdFile, inputs_2_0_V_empty_n, "inputs_2_0_V_empty_n");
    sc_trace(mVcdFile, inputs_2_1_V_full_n, "inputs_2_1_V_full_n");
    sc_trace(mVcdFile, inputs_2_1_V_dout, "inputs_2_1_V_dout");
    sc_trace(mVcdFile, inputs_2_1_V_empty_n, "inputs_2_1_V_empty_n");
    sc_trace(mVcdFile, inputs_2_2_V_full_n, "inputs_2_2_V_full_n");
    sc_trace(mVcdFile, inputs_2_2_V_dout, "inputs_2_2_V_dout");
    sc_trace(mVcdFile, inputs_2_2_V_empty_n, "inputs_2_2_V_empty_n");
    sc_trace(mVcdFile, inputs_3_0_V_full_n, "inputs_3_0_V_full_n");
    sc_trace(mVcdFile, inputs_3_0_V_dout, "inputs_3_0_V_dout");
    sc_trace(mVcdFile, inputs_3_0_V_empty_n, "inputs_3_0_V_empty_n");
    sc_trace(mVcdFile, inputs_3_1_V_full_n, "inputs_3_1_V_full_n");
    sc_trace(mVcdFile, inputs_3_1_V_dout, "inputs_3_1_V_dout");
    sc_trace(mVcdFile, inputs_3_1_V_empty_n, "inputs_3_1_V_empty_n");
    sc_trace(mVcdFile, inputs_3_2_V_full_n, "inputs_3_2_V_full_n");
    sc_trace(mVcdFile, inputs_3_2_V_dout, "inputs_3_2_V_dout");
    sc_trace(mVcdFile, inputs_3_2_V_empty_n, "inputs_3_2_V_empty_n");
    sc_trace(mVcdFile, outputs_0_0_V_full_n, "outputs_0_0_V_full_n");
    sc_trace(mVcdFile, outputs_0_0_V_dout, "outputs_0_0_V_dout");
    sc_trace(mVcdFile, outputs_0_0_V_empty_n, "outputs_0_0_V_empty_n");
    sc_trace(mVcdFile, outputs_0_1_V_full_n, "outputs_0_1_V_full_n");
    sc_trace(mVcdFile, outputs_0_1_V_dout, "outputs_0_1_V_dout");
    sc_trace(mVcdFile, outputs_0_1_V_empty_n, "outputs_0_1_V_empty_n");
    sc_trace(mVcdFile, outputs_0_2_V_full_n, "outputs_0_2_V_full_n");
    sc_trace(mVcdFile, outputs_0_2_V_dout, "outputs_0_2_V_dout");
    sc_trace(mVcdFile, outputs_0_2_V_empty_n, "outputs_0_2_V_empty_n");
    sc_trace(mVcdFile, outputs_0_3_V_full_n, "outputs_0_3_V_full_n");
    sc_trace(mVcdFile, outputs_0_3_V_dout, "outputs_0_3_V_dout");
    sc_trace(mVcdFile, outputs_0_3_V_empty_n, "outputs_0_3_V_empty_n");
    sc_trace(mVcdFile, outputs_1_0_V_full_n, "outputs_1_0_V_full_n");
    sc_trace(mVcdFile, outputs_1_0_V_dout, "outputs_1_0_V_dout");
    sc_trace(mVcdFile, outputs_1_0_V_empty_n, "outputs_1_0_V_empty_n");
    sc_trace(mVcdFile, outputs_1_1_V_full_n, "outputs_1_1_V_full_n");
    sc_trace(mVcdFile, outputs_1_1_V_dout, "outputs_1_1_V_dout");
    sc_trace(mVcdFile, outputs_1_1_V_empty_n, "outputs_1_1_V_empty_n");
    sc_trace(mVcdFile, outputs_1_2_V_full_n, "outputs_1_2_V_full_n");
    sc_trace(mVcdFile, outputs_1_2_V_dout, "outputs_1_2_V_dout");
    sc_trace(mVcdFile, outputs_1_2_V_empty_n, "outputs_1_2_V_empty_n");
    sc_trace(mVcdFile, outputs_1_3_V_full_n, "outputs_1_3_V_full_n");
    sc_trace(mVcdFile, outputs_1_3_V_dout, "outputs_1_3_V_dout");
    sc_trace(mVcdFile, outputs_1_3_V_empty_n, "outputs_1_3_V_empty_n");
    sc_trace(mVcdFile, start_for_kernel_U0_din, "start_for_kernel_U0_din");
    sc_trace(mVcdFile, start_for_kernel_U0_full_n, "start_for_kernel_U0_full_n");
    sc_trace(mVcdFile, start_for_kernel_U0_dout, "start_for_kernel_U0_dout");
    sc_trace(mVcdFile, start_for_kernel_U0_empty_n, "start_for_kernel_U0_empty_n");
    sc_trace(mVcdFile, start_for_write_output_U0_din, "start_for_write_output_U0_din");
    sc_trace(mVcdFile, start_for_write_output_U0_full_n, "start_for_write_output_U0_full_n");
    sc_trace(mVcdFile, start_for_write_output_U0_dout, "start_for_write_output_U0_dout");
    sc_trace(mVcdFile, start_for_write_output_U0_empty_n, "start_for_write_output_U0_empty_n");
    sc_trace(mVcdFile, write_output_U0_start_full_n, "write_output_U0_start_full_n");
    sc_trace(mVcdFile, write_output_U0_start_write, "write_output_U0_start_write");
#endif

    }
    mHdltvinHandle.open("cnn.hdltvin.dat");
    mHdltvoutHandle.open("cnn.hdltvout.dat");
}

cnn::~cnn() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete read_input_U0;
    delete kernel_U0;
    delete write_output_U0;
    delete inputs_0_0_V_U;
    delete inputs_0_1_V_U;
    delete inputs_0_2_V_U;
    delete inputs_1_0_V_U;
    delete inputs_1_1_V_U;
    delete inputs_1_2_V_U;
    delete inputs_2_0_V_U;
    delete inputs_2_1_V_U;
    delete inputs_2_2_V_U;
    delete inputs_3_0_V_U;
    delete inputs_3_1_V_U;
    delete inputs_3_2_V_U;
    delete outputs_0_0_V_U;
    delete outputs_0_1_V_U;
    delete outputs_0_2_V_U;
    delete outputs_0_3_V_U;
    delete outputs_1_0_V_U;
    delete outputs_1_1_V_U;
    delete outputs_1_2_V_U;
    delete outputs_1_3_V_U;
    delete start_for_kernel_U0_U;
    delete start_for_write_ofYi_U;
}

void cnn::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void cnn::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void cnn::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void cnn::thread_in_0_TREADY() {
    in_0_TREADY = read_input_U0_in_0_TREADY.read();
}

void cnn::thread_in_1_TREADY() {
    in_1_TREADY = read_input_U0_in_1_TREADY.read();
}

void cnn::thread_in_2_TREADY() {
    in_2_TREADY = read_input_U0_in_2_TREADY.read();
}

void cnn::thread_in_3_TREADY() {
    in_3_TREADY = read_input_U0_in_3_TREADY.read();
}

void cnn::thread_kernel_U0_ap_continue() {
    kernel_U0_ap_continue = ap_const_logic_1;
}

void cnn::thread_kernel_U0_ap_start() {
    kernel_U0_ap_start = start_for_kernel_U0_empty_n.read();
}

void cnn::thread_out_0_TDATA() {
    out_0_TDATA = write_output_U0_out_0_TDATA.read();
}

void cnn::thread_out_0_TKEEP() {
    out_0_TKEEP = write_output_U0_out_0_TKEEP.read();
}

void cnn::thread_out_0_TLAST() {
    out_0_TLAST = write_output_U0_out_0_TLAST.read();
}

void cnn::thread_out_0_TSTRB() {
    out_0_TSTRB = write_output_U0_out_0_TSTRB.read();
}

void cnn::thread_out_0_TVALID() {
    out_0_TVALID = write_output_U0_out_0_TVALID.read();
}

void cnn::thread_out_1_TDATA() {
    out_1_TDATA = write_output_U0_out_1_TDATA.read();
}

void cnn::thread_out_1_TKEEP() {
    out_1_TKEEP = write_output_U0_out_1_TKEEP.read();
}

void cnn::thread_out_1_TLAST() {
    out_1_TLAST = write_output_U0_out_1_TLAST.read();
}

void cnn::thread_out_1_TSTRB() {
    out_1_TSTRB = write_output_U0_out_1_TSTRB.read();
}

void cnn::thread_out_1_TVALID() {
    out_1_TVALID = write_output_U0_out_1_TVALID.read();
}

void cnn::thread_read_input_U0_ap_continue() {
    read_input_U0_ap_continue = ap_const_logic_1;
}

void cnn::thread_read_input_U0_ap_start() {
    read_input_U0_ap_start = ap_const_logic_1;
}

void cnn::thread_start_for_kernel_U0_din() {
    start_for_kernel_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void cnn::thread_start_for_write_output_U0_din() {
    start_for_write_output_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void cnn::thread_write_output_U0_ap_continue() {
    write_output_U0_ap_continue = ap_const_logic_1;
}

void cnn::thread_write_output_U0_ap_start() {
    write_output_U0_ap_start = start_for_write_output_U0_empty_n.read();
}

void cnn::thread_write_output_U0_start_full_n() {
    write_output_U0_start_full_n = ap_const_logic_1;
}

void cnn::thread_write_output_U0_start_write() {
    write_output_U0_start_write = ap_const_logic_0;
}

void cnn::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"in_0_TDATA\" :  \"" << in_0_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_1_TDATA\" :  \"" << in_1_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_2_TDATA\" :  \"" << in_2_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_3_TDATA\" :  \"" << in_3_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_0_TKEEP\" :  \"" << in_0_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_1_TKEEP\" :  \"" << in_1_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_2_TKEEP\" :  \"" << in_2_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_3_TKEEP\" :  \"" << in_3_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_0_TSTRB\" :  \"" << in_0_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_1_TSTRB\" :  \"" << in_1_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_2_TSTRB\" :  \"" << in_2_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_3_TSTRB\" :  \"" << in_3_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_0_TLAST\" :  \"" << in_0_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_1_TLAST\" :  \"" << in_1_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_2_TLAST\" :  \"" << in_2_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_3_TLAST\" :  \"" << in_3_TLAST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"out_0_TDATA\" :  \"" << out_0_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1_TDATA\" :  \"" << out_1_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_0_TKEEP\" :  \"" << out_0_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1_TKEEP\" :  \"" << out_1_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_0_TSTRB\" :  \"" << out_0_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1_TSTRB\" :  \"" << out_1_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_0_TLAST\" :  \"" << out_0_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1_TLAST\" :  \"" << out_1_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_0_TVALID\" :  \"" << in_0_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_0_TREADY\" :  \"" << in_0_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_1_TVALID\" :  \"" << in_1_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_1_TREADY\" :  \"" << in_1_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_2_TVALID\" :  \"" << in_2_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_2_TREADY\" :  \"" << in_2_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_3_TVALID\" :  \"" << in_3_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_3_TREADY\" :  \"" << in_3_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_0_TVALID\" :  \"" << out_0_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_0_TREADY\" :  \"" << out_0_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1_TVALID\" :  \"" << out_1_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_1_TREADY\" :  \"" << out_1_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

