#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("in_0_TDATA", 64, hls_in, 0, "axis", "in_data", 1),
	Port_Property("in_1_TDATA", 64, hls_in, 1, "axis", "in_data", 1),
	Port_Property("in_2_TDATA", 64, hls_in, 2, "axis", "in_data", 1),
	Port_Property("in_3_TDATA", 64, hls_in, 3, "axis", "in_data", 1),
	Port_Property("in_0_TKEEP", 8, hls_in, 4, "axis", "in_data", 1),
	Port_Property("in_1_TKEEP", 8, hls_in, 5, "axis", "in_data", 1),
	Port_Property("in_2_TKEEP", 8, hls_in, 6, "axis", "in_data", 1),
	Port_Property("in_3_TKEEP", 8, hls_in, 7, "axis", "in_data", 1),
	Port_Property("in_0_TSTRB", 8, hls_in, 8, "axis", "in_data", 1),
	Port_Property("in_1_TSTRB", 8, hls_in, 9, "axis", "in_data", 1),
	Port_Property("in_2_TSTRB", 8, hls_in, 10, "axis", "in_data", 1),
	Port_Property("in_3_TSTRB", 8, hls_in, 11, "axis", "in_data", 1),
	Port_Property("in_0_TLAST", 1, hls_in, 12, "axis", "in_data", 1),
	Port_Property("in_1_TLAST", 1, hls_in, 13, "axis", "in_data", 1),
	Port_Property("in_2_TLAST", 1, hls_in, 14, "axis", "in_data", 1),
	Port_Property("in_3_TLAST", 1, hls_in, 15, "axis", "in_data", 1),
	Port_Property("out_0_TDATA", 64, hls_out, 16, "axis", "out_data", 1),
	Port_Property("out_1_TDATA", 64, hls_out, 17, "axis", "out_data", 1),
	Port_Property("out_0_TKEEP", 8, hls_out, 18, "axis", "out_data", 1),
	Port_Property("out_1_TKEEP", 8, hls_out, 19, "axis", "out_data", 1),
	Port_Property("out_0_TSTRB", 8, hls_out, 20, "axis", "out_data", 1),
	Port_Property("out_1_TSTRB", 8, hls_out, 21, "axis", "out_data", 1),
	Port_Property("out_0_TLAST", 1, hls_out, 22, "axis", "out_data", 1),
	Port_Property("out_1_TLAST", 1, hls_out, 23, "axis", "out_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("in_0_TVALID", 1, hls_in, 12, "axis", "in_vld", 1),
	Port_Property("in_0_TREADY", 1, hls_out, 12, "axis", "in_acc", 1),
	Port_Property("in_1_TVALID", 1, hls_in, 13, "axis", "in_vld", 1),
	Port_Property("in_1_TREADY", 1, hls_out, 13, "axis", "in_acc", 1),
	Port_Property("in_2_TVALID", 1, hls_in, 14, "axis", "in_vld", 1),
	Port_Property("in_2_TREADY", 1, hls_out, 14, "axis", "in_acc", 1),
	Port_Property("in_3_TVALID", 1, hls_in, 15, "axis", "in_vld", 1),
	Port_Property("in_3_TREADY", 1, hls_out, 15, "axis", "in_acc", 1),
	Port_Property("out_0_TVALID", 1, hls_out, 22, "axis", "out_vld", 1),
	Port_Property("out_0_TREADY", 1, hls_in, 22, "axis", "out_acc", 1),
	Port_Property("out_1_TVALID", 1, hls_out, 23, "axis", "out_vld", 1),
	Port_Property("out_1_TREADY", 1, hls_in, 23, "axis", "out_acc", 1),
};
const char* HLS_Design_Meta::dut_name = "cnn";
